### PR TITLE
[ADP 3491] Relax policy key guard

### LINKED ISSUE #4872: Issue with constructTransaction endpoint for a wallet created from xpub
### Just checking...

- [X] This is a `cardano-wallet` bug.
- [X] I am using the latest `cardano-wallet` release.
- [X] I am using the *correct* `cardano-node` version for that release of `cardano-wallet`.

### Version

v2024-11-18

### Platform

macOS 14

### Installation method

Nix

### Network configuration

preview

### Context

In the Daedalus, we serve HWs by restoring them in the Cardano Wallet using their `account_public_key`. Those wallets are having an issue calling the `constructTransaction` endpoint.

## Steps to Reproduce

1. Restore a wallet in Cardano Wallet using its `account_public_key`
2. Call the [constructTransaction](https://cardano-foundation.github.io/cardano-wallet/api/edge/#operation/constructTransaction) endpoint with `{ vote: 'abstain' }` payload

### Expected behavior

TX with votes delegation is correctly constructed

### Actual behavior

Receiving an `missing_policy_public_key` error in response

### PR DESCRIPTION
**Pull request by paweljakubas**
`policyXPub` is needed in constructTransaction in two cases:
- tx contains minting/burning action
- tx deals with reference scripting and has reference script template nonempty

instead of using `policyXPub` we use `policyXPubM` throught the function and only deconstruct it when checking those two cases. `ErrReadPolicyPublicKeyAbsen` is used for the those two valid situations when policy xpub is missing.

### Issue Number

Fix https://github.com/cardano-foundation/cardano-wallet/issues/4872

### CODE REVIEW

File: lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs [hunk 1]
```diff
@@ -2650,7 +2653,7 @@ constructTransaction api knownPools poolStatus apiWalletId body = do
                             makeLeft $
                             toTokenMapAndScript ShelleyKeyS
                                 scriptT
-                                (Map.singleton (Cosigner 0) policyXPub)
+                                (Map.singleton (Cosigner 0) $ fromJust policyXPubM)
```
Comment (Anviking) [inline lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs]: 🤔 Having to resort to an approach with `fromJust` seems unfortunate...

Comment (paweljakubas) [reply lib/api/src/Cardano/Wallet/Api/Http/Shelley/Server.hs]: yeah, fair point. Now no partial function fixing ;-)

**Comment by paweljakubas** [comment]
waiting for the daedalus team to confirm if the fix works. If yes then we will undraft it.

**Comment by abailly** [comment]
There's a remaining issue: `constructTransaction` depends on `decodeTransaction` which unconditionally extract the policy pub key and throws an exception if it cannot find one.

**Comment by abailly** [comment]
Fix #4872

**Comment by Anviking** [comment]
@abailly the last commit is huge (+3,919 −3,109). Unintentionally caused by some autoformatter?

**Comment by abailly** [comment]
@Anviking I don't know, I ran the code checker and it did not complain 🤷

**Comment by abailly** [comment]
I must confess I pay exactly 0 attention to code format as I expect this to be handled by the tooling. In our case, I understand this is stylish-haskell, which I ran.

**Comment by abailly** [comment]
@paweljakubas I think I would like to write a proper test for this, your guidance would be much appreciated.

**Comment by paweljakubas** [comment]
The most beautiful (and persuasive also) test (integration one) would be the following:
1. Create wallet with funds, `walMnemonic`
2. Get extended account public key from walMnemonic, `xAcctPub`
3.  Create account public key wallet from `xAcctPub`, `walAcct`
4. Create constructTransation for `walAcct` that joinDep in conway only (no babbage)
5. Hand over cbor of point 4 to `walMnemonic` and sign and submit it 
6. Make sure both `walAcct` and `walMnemonic` are voting.

In essense, `walMnemonic` can be treated as hardware wallet.

**Comment by abailly** [comment]
@Anviking I updated the PR, the size of the diff is much more reasonable :)
I really wish we move to a formatter that actually enforces proper formatting, eg. ormolu or fourmolu, in order to streamline this whole thing

**Review by Anviking — APPROVED** [review]
lgtm, if you've tested this. I suspect the `fromJust` pattern could be dropped but that already existed before this pr.

**Comment by abailly** [comment]
@Anviking I agree an integration test would be useful, but I also don't want to add too many of those as they might become a liability pretty quickly.

**Comment by Anviking** [comment]
Yeah, I just meant that I presume you've verified (manually) that this did what you wanted it to

**Comment by abailly** [comment]
Of course, but you're right and this feels a bit sloppy

**Comment by Anviking** [comment]
> but I also don't want to add too many of those as they might become a liability pretty quickly.

Fully share this concern though
