### PR TITLE
Save intermediate state when restoring the Byron chain in the stake pools worker

### LINKED ISSUE #1963: Stake pool DB worker doesn't save sync progress in Byron
# Context
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      |  |
| Platform     |           |
| Installation |             |

# Steps to Reproduce

1. Start a `cardano-node` connected to the byron mainnet
1. `cardano-wallet-shelley serve --node-socket socket --mainnet --database wallet-db`
2. wait 20 s
3. `ctrl-c`
4. `cardano-wallet-shelley serve --node-socket socket --mainnet --database wallet-db`

## Expected behavior

The sync progress from the first launch is saved, and it doesn't have to start from the beginning after quitting.

## Actual behavior

It restarts from genesis the second time.

Syncing through the whole of byron again may take some time. I guess it takes ~10 minutes on my machine, if the node is already synced, so while not optimal, I believe it should be fine for now.
 

---

# Resolution 

---

# QA 

Currently there are no integration tests. All we do is test the `putHeaders` and `listHeaders` DBLayer functions: https://github.com/input-output-hk/cardano-wallet/pull/2138/files#diff-c3e090fb717915e32577d1c7311e8ab5392c830dec9a705e025f0bf84af6b099

This tests the new table `block_headers`.

Testing that the wallet resumes the chain at a certain point is very easy on testnet though. Starting sync process, crtl+c and start wallet again. Then check that it resumes on the previous block height.

### PR DESCRIPTION
**Pull request by hasufell**
This completely skips byron era for mainnet when syncing stake pools.

I extracted the first shelley block by looking at a fully synced stake pool DB and selecting the lowest `block_height` from the `pool_production` table.

For non-mainnet it will record the last byron block of a chunk from the node into the `byron_headers` table and read it out during `readPoolProductionCursor` if there are no stake pools and otherwise ignore it.

Remarks:

- the "genesis shelley header" is hardcoded, because the node currently does not have an endpoint to get this

### CODE REVIEW

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 1]
```diff
@@ -494,8 +494,24 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
+            -- networks.
+            -- TODO: query cardano-node for hard fork block (not yet possible)
+            genesisShelleyHeader :: BlockHeader
+            genesisShelleyHeader = BlockHeader
+                (SlotNo 4492800)
+                (Quantity 4490511)
+                (either (error . show) id $
+                    fromText "aa83acbf5904c0edfe4d79b3689d3d00fcfc553cf360fd2229b98d464c28e9de")
+                (either (error . show) id $
+                    fromText "f8084c61b6a238acec985b59310b6ecec49c0ab8352249afd7268da5cff2a457")
```
Comment (KtorZ) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: use instead: https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/src/Cardano/Wallet/Unsafe.hs#L90

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 2]
```diff
@@ -494,8 +494,24 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
     mkLatestGarbageCollectionEpochRef = newIORef minBound
 
     initCursor :: IO [BlockHeader]
-    initCursor = atomically $ readPoolProductionCursor (max 100 k)
+    initCursor = do
+        fromDB <- atomically $ readPoolProductionCursor (max 100 k)
+        case fromDB of
+            [] -> pure [genesisShelleyHeader]
+            xs -> pure xs
```
Comment (KtorZ) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: Note that this is (almost) equivalent to: `genesisShelleyHeader:xs`. When looking for an intersection, the node look at intersection points in order. The last item of that list is considered the "most interesting" point.

**Comment by hasufell** [comment]
Are there any interesting tests @piotr-iohk you can think of?

**Comment by piotr-iohk** [comment]
> Are there any interesting tests @piotr-iohk you can think of?

I suppose performance improvements may be visible on the [nightly benchmars](https://buildkite.com/input-output-hk/cardano-wallet-nightly) once they land in master. It's possible also to trigger those benchmarks manually on branch.
Are we anticipating improvements in wallet restoration time?

As for issue described in #1963, I suppose the only way to test is manually. (In integration tests we currently start tests after hard fork happens.)

File: lib/core/src/Cardano/Pool/DB/Model.hs [hunk 3]
```diff
@@ -181,6 +188,18 @@ mPutPoolProduction point poolId db@PoolDatabase{pools} =
         , db { pools = Map.alter (alter point) poolId pools }
         )
 
+mPutByronHeader :: BlockHeader -> ModelPoolOp ()
+mPutByronHeader point db@PoolDatabase{byronHeaders} =
+    ( Right ()
+    , db { byronHeaders = point:byronHeaders })
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Model.hs]: Hi @hasufell.

We revised the `Pool.DB.Model` module quite a bit in https://github.com/input-output-hk/cardano-wallet/pull/2132.

So you'd now probably need to write something like this:
```suggestion
mPutByronHeader :: BlockHeader -> ModelOp ()      
mPutByronHeader header = modify #byronHeaders (header :)  
```

Also, I noticed that the model implementation don't check to see if the point is already in the list. Should we check? We do appear check for this in the SQLite implementation:

```hs
        putByronHeader point = ExceptT $
            handleConstraint (ErrPointAlreadyExists point) $
                let record = mkByronHeader point
                    key = byronBlockHeight record
                in repsert (ByronHeadersKey key) record
```

File: lib/core/src/Cardano/Pool/DB/Model.hs [hunk 4]
```diff
@@ -181,6 +188,18 @@ mPutPoolProduction point poolId db@PoolDatabase{pools} =
...
+
+mListByronHeaders :: Int -> PoolDatabase -> ([BlockHeader], PoolDatabase)
+mListByronHeaders k db@PoolDatabase{byronHeaders} =
+    (take k byronHeaders, db)
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Model.hs]: With the revised `ModelOp` type, we can write the function like this:

```suggestion
mListByronHeaders :: Int -> ModelOp [BlockHeader]     
mListByronHeaders k = take k <$> get #byronHeaders
```

File: lib/core/src/Cardano/Pool/DB/Model.hs [hunk 5]
```diff
@@ -181,6 +188,18 @@ mPutPoolProduction point poolId db@PoolDatabase{pools} =
...
+
+mDropByronHeaders :: ModelPoolOp ()
+mDropByronHeaders db = (Right (), db { byronHeaders = [] })
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Model.hs]: With the revised `ModelOp` type, we can write this function like this:

```suggestion
mDropByronHeaders :: ModelOp ()
mDropByronHeaders = modify #byronHeaders (const [])
```

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 6]
```diff
@@ -554,6 +560,23 @@ newDBLayer trace fp timeInterpreter = do
...
+
+        listByronHeaders k = do
+            fmap (fromByronHeaders . entityVal) <$> selectList [ ]
+                [ Desc ByronBlockHeight
+                , LimitTo k
+                ]
+
+        dropByronHeaders =
+            let query = [s|DELETE FROM byron_headers;|]
+            in rawExecute query []
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]: This SQL query looks perfectly fine to me, but I wonder if  `persistent` has an equivalent that would mean we could avoid SQL here?

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 7]
```diff
@@ -468,9 +469,14 @@ newDBLayer trace fp timeInterpreter = do
                 . MsgRemovingRetiredPools
 
         readPoolProductionCursor k = do
-            reverse . map (snd . fromPoolProduction . entityVal) <$> selectList
+            pp <- reverse . map (snd . fromPoolProduction . entityVal) <$> selectList
                 []
                 [Desc PoolProductionSlot, LimitTo k]
+            case pp of
+                -- byron headers might not be inserted
+                -- continously, so only pick the last
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]: Small typo:
```suggestion
                -- continuously, so only pick the last.
```

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 8]
```diff
@@ -494,8 +498,22 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
+            -- networks.
+            -- TODO: query cardano-node for hard fork block (not yet possible)
+            genesisShelleyHeader :: BlockHeader
+            genesisShelleyHeader = BlockHeader
+                (SlotNo 4492800)
+                (Quantity 4490511)
+                (Hash $ unsafeFromHex
+                    "aa83acbf5904c0edfe4d79b3689d3d00fcfc553cf360fd2229b98d464c28e9de")
+                (Hash $ unsafeFromHex
+                    "f8084c61b6a238acec985b59310b6ecec49c0ab8352249afd7268da5cff2a457")
```
Comment (jonathanknowles) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: A couple of suggestions:

1. Move this definition to the top-level, and change the comment to a Haddock-style comment.
2. Make the name of the constant clearly indicate that it's for `mainnet`. So, perhaps something like `mainnetGenesisShelleyHeader` or `mainnetShelleyGenesisHeader`?

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 9]
```diff
@@ -506,24 +524,35 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
+                        garbageCollectPools slot latestGarbageCollectionEpochRef
+                        putPoolCertificates slot certificates
+
+            -- We store the last byron header in the chunk only to have a sync point,
+            -- when syncing was interrupted.
+            case NE.last blocks of
+                BlockByron blk -> do
+                  dropByronHeaders
+                  handleErr (putByronHeader (toByronBlockHeader gp blk))
+                BlockShelley _ -> pure ()
```
Comment (jonathanknowles) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: **Suggestion**: Perhaps break up this section a bit, to reduce the level of nesting?

Something like:

```hs
atomically $
    processBlocksByron blocks
    processBlocksShelley blocks
```
And then define:
```hs
processBlocksShelley blocks =
    forM_ blocks $ \case
    BlockByron _ ->
        ...
    BlockShelley blk -> do
        -- Record pool certificates
        ...

processBlocksByron blocks = 
    case NE.last blocks of
        BlockByron blk ->
            dropByronHeaders
                handleErr (putByronHeader (toByronBlockHeader gp blk))
        BlockShelley _ -> 
            ...
```

File: lib/core/src/Cardano/Pool/DB/MVar.hs [hunk 10]
```diff
@@ -151,6 +154,16 @@ newDBLayer timeInterpreter = do
                 removePools (view #poolId <$> retirementCerts)
                 pure retirementCerts
 
+        putByronHeader point = ExceptT $
+            point `deepseq`
+                (alterPoolDB errPointAlreadyExists db $ mPutByronHeader point)
+
+        listByronHeaders k =
+            modifyMVar db (pure . swap . mListByronHeaders k)
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/MVar.hs]: Request: use `readPoolDB` if possible, as it's a read-only operation.

```suggestion
        listByronHeaders =
            readPoolDB db . mListByronHeaders
```

**Review by jonathanknowles — CHANGES_REQUESTED** [review]
Hi @hasufell 

This looks good so far. :+1: 

I have a few suggestions (see review comments), and a couple of requests:

- Use `readPoolDB` within `listByronHeaders` (https://github.com/input-output-hk/cardano-wallet/pull/2138#discussion_r488404944).
- We should probably add some **property tests** for the newly-added DB operations. We're currently in the middle of [adjusting](https://github.com/input-output-hk/cardano-wallet/pull/2136) our [pool DB property test suite](https://github.com/input-output-hk/cardano-wallet/blob/master/lib/core/test/unit/Cardano/Pool/DB/Properties.hs) so that it can test both the model and SQLite implementations. So whatever properties we write should pass with both implementations.

Also, we recently changed the type of `ModelOp` for the pool database. So there will be some changes necessary here. However, I've added comments to the PR showing how to make these changes. Let me know if I can help in any way!

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 11]
```diff
@@ -494,8 +498,22 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
 
     initCursor :: IO [BlockHeader]
-    initCursor = atomically $ readPoolProductionCursor (max 100 k)
+    initCursor = do
+        fromDB <- atomically $ readPoolProductionCursor (max 100 k)
+        pure (genesisShelleyHeader:fromDB)
       where k = fromIntegral $ getQuantity getEpochStability
+            -- We only have stake pools since shelley era.
+            -- This is hardcoded for mainnet and will do nothing for other
+            -- networks.
```
Comment (Anviking) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: Neat!

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 8 above)
Comment (Anviking) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: I'm not sure the name "genesis" here actually makes sense. I think the Shelley genesis file is used for the hard-fork, but doesn't actually correspond to the first Shelley block.

Even so, wouldn't you want `finalByronBlockHeader` instead, such that the node gives you the first Shelley block and not the second?

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 12]
```diff
@@ -494,8 +498,22 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
+            -- TODO: query cardano-node for hard fork block (not yet possible)
```
Comment (Anviking) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: > not **yet** possible

Is there something suggesting that it _will_ be?

File: lib/core/src/Cardano/Pool/DB/Model.hs (hunk 3 above)
Comment (hasufell) [reply lib/core/src/Cardano/Pool/DB/Model.hs]: `repsert` will overwrite, so the catching here seems unnecessary

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs (hunk 6 above)
Comment (hasufell) [reply lib/core/src/Cardano/Pool/DB/Sqlite.hs]: I couldn't find it.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 8 above)
Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: @jonathanknowles 

> Move this definition to the top-level, and change the comment to a Haddock-style comment.

What would be the reason for that? It's only used once. I usually prefer to not pollute the module namespace, unless it's really a shared entity.

> Make the name of the constant clearly indicate that it's for

What about `firstShelleyBlockMainnet`?

----

@Anviking 

> Even so, wouldn't you want finalByronBlockHeader instead, such that the node gives you the first Shelley block and not the second?

You're absolutely right. I double checked this in the sqlite database and we need the last byron header indeed.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 12 above)
Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: My intention to file a feature request!

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs (hunk 6 above)
Comment (KtorZ) [reply lib/core/src/Cardano/Pool/DB/Sqlite.hs]: `deleteWhere []`

Comment (KtorZ) [reply lib/core/src/Cardano/Pool/DB/Sqlite.hs]: with a proper type annotation on `[]` to let persistent know what table.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 12 above)
Comment (KtorZ) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: Let's open the ticket first, and reference it from the TODO comment.

Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: https://jira.iohk.io/browse/CAD-1850

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 9 above)
Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: Though about it. But I think it might tempt someone to use two forM blocks by accident, which would be a performance penalty. This way we can see that we want to do as little processing as possible.

Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: In fact, we're already traversing twice due to `NE.last`... I'll try to fix that

Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]:
```hs
        -- | Like 'forM_', except runs the second action for the last element as
        -- well (in addition to the first action).
        forML_ :: (Monad m)
            => [a]
            -> (a -> m b) -- ^ action to run for all elements
            -> (a -> m c) -- ^ action to run for the last element
            -> m ()
        forML_ []  _ _ = pure ()
        forML_ [x] a1 a2 = a1 x >> a2 x >> forML_ [] a1 a2
        forML_ (x:xs) a1 a2 = a1 x >> forML_ xs a1 a2
```

**Comment by hasufell** [comment]
@Anviking We should test that this change didn't affect the sync time overall for non-mainnet syncs (e.g. because of the additional inserts).

I have to run a few more tests, but I think for mainnet the sync time degraded from 5 minutes to 8 minutes on my PC (when not utilizing the last byron block).

Edit: I decided to use a counter and only insert every 50.000th block header. There seems to be no performance degredation.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 9 above)
Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: Surprisingly, this made it slower... maybe the other form has better list fusion/inlining and memoization.

Comment (Anviking) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: What if you write the _first_ byron block header instead of the _last_, does that help?

The checkpoint will be a bit (1000 blocks?) old, but I can't see how that would matter.

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 13]
```diff
@@ -554,6 +559,20 @@ newDBLayer trace fp timeInterpreter = do
...
+                    key = byronBlockHeight record
+                in repsert (ByronHeadersKey key) record
+
+        listByronHeaders k = do
+            fmap (fromByronHeaders . entityVal) <$> selectList [ ]
+                [ Desc ByronBlockHeight
+                , LimitTo k
+                ]
+
+        dropByronHeaders = deleteWhere @_ @_ @ByronHeaders []
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]: :+1:

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 14]
```diff
@@ -837,6 +856,21 @@ fromPoolProduction (PoolProduction pool slot headerH parentH height) =
...
+    { byronSlot = view #slotNo block
+    , byronHeaderHash = BlockId (headerHash block)
+    , byronParentHash = BlockId (parentHeaderHash block)
+    , byronBlockHeight = getQuantity (blockHeight block)
+    }
+
+fromByronHeaders :: ByronHeaders -> BlockHeader
+fromByronHeaders ByronHeaders { .. } =
+    BlockHeader byronSlot (Quantity byronBlockHeight) (getBlockId byronHeaderHash)
+        (getBlockId byronParentHash)
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]: https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards#limit-line-length-to-80-characters

```suggestion
    BlockHeader byronSlot
        (Quantity byronBlockHeight)
        (getBlockId byronHeaderHash)
        (getBlockId byronParentHash)
```

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 15]
```diff
@@ -494,36 +499,81 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
+            --       https://jira.iohk.io/browse/CAD-1850
+            lastByronBlock :: BlockHeader
+            lastByronBlock = BlockHeader
+                (SlotNo 4492799)
+                (Quantity 4490510)
+                (Hash $ unsafeFromHex
+                    "f8084c61b6a238acec985b59310b6ecec49c0ab8352249afd7268da5cff2a457")
+                (Hash $ unsafeFromHex
+                    "aa83acbf5904c0edfe4d79b3689d3d00fcfc553cf360fd2229b98d464c28e9de")
```
Comment (jonathanknowles) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: I still think this would be better as a top-level constant.

Embedding this as a nested constant means that it's doesn't fit within our [line limit](https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards#limit-line-length-to-80-characters).

But by moving this to the top-level, we can completely avoid this problem.

As a bonus, we can add a Haddock comment:

```suggestion
-- | The very last block header of the Byron era, just before the transition
--   to Shelley.
-- 
-- This is hard-coded for mainnet and will do nothing for other networks.
--
-- TODO: query cardano-node for hard fork block (not yet possible).
-- https://jira.iohk.io/browse/CAD-1850
--
lastByronBlock :: BlockHeader
lastByronBlock = BlockHeader
    (SlotNo 4492799)
    (Quantity 4490510)
    (Hash $ unsafeFromHex
        "f8084c61b6a238acec985b59310b6ecec49c0ab8352249afd7268da5cff2a457")
    (Hash $ unsafeFromHex
        "aa83acbf5904c0edfe4d79b3689d3d00fcfc553cf360fd2229b98d464c28e9de")
```

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 16]
```diff
@@ -494,36 +499,81 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
                     -- retired.
                     garbageCollectPools slot latestGarbageCollectionEpochRef
                     putPoolCertificates slot certificates
-        pure Continue
+
+        {-# INLINE forLastBlock #-}
+        forLastBlock = \case
+            BlockByron blk -> do
+                c <- liftIO $ readIORef chunkCounter
+                when (c `mod` 50 == 0) $ do -- every 50k blocks, insert a header
```
Comment (jonathanknowles) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: Is it possible that we might repeatedly skip over this condition? As far as I know, we don't really control how many blocks we're given by the block following protocol. Suppose we're initially given 10 blocks, and then from that point forward, repeatedly given 50 blocks? Would the `c mod 50` condition not then would always evaluate to `10`?

What if instead we just write a header once per epoch? We already track the _last-seen epoch_ in the `mkLatestGarbageCollectionEpochRef`. Perhaps there is a way to reuse that reference here, and make it into a more general purpose reference of the "last-seen epoch"?

Whenever we get a new set of blocks, we can check whether or not we've transitioned into a new epoch, and if so:

 1. Write a new block header (if we're in the Byron era).
 2. Perform garbage collection of retired pools (if we're in the Shelley era).
 3. Update the latest epoch reference.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 17]
```diff
@@ -494,36 +499,81 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
 
     forward
         :: IORef EpochNo
+        -> IORef Int
         -> NonEmpty (CardanoBlock sc)
         -> (BlockHeader, ProtocolParameters)
         -> IO (FollowAction ())
-    forward latestGarbageCollectionEpochRef blocks (_nodeTip, _pparams) = do
-        atomically $ forM_ blocks $ \case
+    forward latestGarbageCollectionEpochRef chunkCounter blocks (_nodeTip, _pparams) = do
```
Comment (jonathanknowles) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]:
```suggestion
    forward latestGarbageCollectionEpochRef chunkCounter blocks _ = do
```

(Tangentially: https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards#limit-line-length-to-80-characters)

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 18]
```diff
@@ -468,9 +468,14 @@ newDBLayer trace fp timeInterpreter = do
...
         readPoolProductionCursor k = do
-            reverse . map (snd . fromPoolProduction . entityVal) <$> selectList
+            pp <- reverse . map (snd . fromPoolProduction . entityVal) <$> selectList
                 []
                 [Desc PoolProductionSlot, LimitTo k]
+            case pp of
+                -- byron headers might not be inserted
+                -- continuously, so only pick the last.
+                [] -> listByronHeaders 1
+                xs -> pure xs
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]: Request: make this a bit shorter. (See [line limit](https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards#limit-line-length-to-80-characters).)

Here's one potentially nice way:
```suggestion
            pp <- map (snd . fromPoolProduction . entityVal) <$> selectList
                []
                [Desc PoolProductionSlot, LimitTo k]
            case pp of
                -- byron headers might not be inserted
                -- continuously, so only pick the last.
                [] -> listByronHeaders 1
                xs -> pure $ reverse xs
```

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 19]
```diff
@@ -554,6 +559,20 @@ newDBLayer trace fp timeInterpreter = do
...
+
+        listByronHeaders k = do
+            fmap (fromByronHeaders . entityVal) <$> selectList [ ]
+                [ Desc ByronBlockHeight
+                , LimitTo k
+                ]
+
+        dropByronHeaders = deleteWhere @_ @_ @ByronHeaders []
+
+
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]:
```suggestion

```

File: lib/core/src/Cardano/Pool/DB/Model.hs [hunk 20]
```diff
@@ -396,6 +403,15 @@ mRemoveRetiredPools epoch = do
     mRemovePools (view #poolId <$> certificates)
     pure certificates
 
+mPutByronHeader :: BlockHeader -> ModelOp ()      
+mPutByronHeader header = modify #byronHeaders (header :)
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Model.hs]: :+1: 

This is much more concise!

File: lib/core/src/Cardano/Pool/DB/Model.hs [hunk 21]
```diff
@@ -396,6 +403,15 @@ mRemoveRetiredPools epoch = do
     mRemovePools (view #poolId <$> certificates)
     pure certificates
 
+mPutByronHeader :: BlockHeader -> ModelOp ()      
+mPutByronHeader header = modify #byronHeaders (header :)  
+
+mListByronHeaders :: Int -> ModelOp [BlockHeader]     
+mListByronHeaders k = take k <$> get #byronHeaders
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Model.hs]: :+1:

File: lib/core/src/Cardano/Pool/DB/Model.hs [hunk 22]
```diff
@@ -396,6 +403,15 @@ mRemoveRetiredPools epoch = do
...
+
+mDropByronHeaders :: ModelOp ()
+mDropByronHeaders = modify #byronHeaders (const [])
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Model.hs]: :+1:

File: lib/core/src/Cardano/Pool/DB/MVar.hs [hunk 23]
```diff
@@ -146,6 +149,15 @@ newDBLayer timeInterpreter = do
                 . alterPoolDB (const Nothing) db
                 . mRemoveRetiredPools
 
+        putByronHeader point =
+            void . alterPoolDB (const Nothing) db . mPutByronHeader $ point
+
+        listByronHeaders =
+            readPoolDB db . mListByronHeaders
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/MVar.hs]: :+1:

File: lib/core/src/Cardano/Pool/DB.hs [hunk 24]
```diff
@@ -223,6 +223,20 @@ data DBLayer m = forall stm. (MonadFail stm, MonadIO stm) => DBLayer
...
+    , putByronHeader
+        :: BlockHeader
+        -> stm ()
+        -- ^ Add a byron header
+
+    , listByronHeaders
+        :: Int -- ^ limit
+        -> stm [BlockHeader]
+        -- ^ List byron headers, usually stored during syncing
+        --
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB.hs]:
```suggestion
```

**Review by jonathanknowles — CHANGES_REQUESTED** [review]
Hi @hasufell 

Many thanks for the update! I see there have been quite a few improvements.

I still have three concerns:

1. Given that we only need to write a block header to the database occasionally, I can't help wondering whether there isn't a simpler way to handle this? We already track transitions across epoch boundaries in order to limit the garbage collection of retired pools: can we not reuse the same technique (and even the same reference) to decide when to write block headers? I'm also concerned that the existing logic might inadvertently fail to fire (though I could be wrong about this). See my comment [here](https://github.com/input-output-hk/cardano-wallet/pull/2138#discussion_r488659342) for more info.

2. There don't seem to be any property tests just yet. I think it would be worth adding some basic property tests for the new DB operations, in the same style as those in `lib/core/test/unit/Cardano/Pool/DB/Properties.hs`.

3. There are some other coding standards issues that should really be fixed. (See comments.) I've added a suggestion for each one, so it should be fast to fix these.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 25]
```diff
@@ -494,36 +499,89 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
+        {-# INLINE forLastBlock #-}
+        forLastBlock = \case
+            BlockByron blk -> do
+                c <- liftIO $ readIORef chunkCounter
+                when (c `mod` 50 == 0) $ do -- every 50k blocks, insert a header
+                    putByronHeader (toByronBlockHeader gp blk)
+                liftIO $ modifyIORef' chunkCounter (+1)
+            BlockShelley _ -> pure ()
+
+        {-# INLINE handleErr #-}
```
Comment (KtorZ) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: Leave inlines to the compiler by default. Add a pragma if it appears to be necessary.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 16 above)
Comment (KtorZ) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: What is this even needed? Writing one block header every batch isn't going to be very costly. `forLastBlock` could be simplified to write block headers to the database everytime it is called, there's no need for further filtering.

Comment (KtorZ) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: More importantly, the point of writing those headers is to maintain a list of candidates that'll be used for finding an intersection in case the system restart. So, having gaps of 50k blocks (or even, of an entire epoch) is _not acceptable_. 

The chain follower implementation will yield blocks by batches while syncing far from the tip, and once reaching the "unstable edge" (i.e. k blocks from the network tip), it'll start yielding them in a slower fashion. In practice, we want to have some a high density of blocks near the tip, and can resort to a sparse view for deeper blocks. This is implemented by the `sparseCheckpoints` function in `Cardano.Wallet.DB` which gives you a list of block numbers to preserve given `k` and a current chain height

Comment (KtorZ) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: The approach taken for wallet workers is to always store the last block received from the chain follower and, regularly _prune_ old checkpoints that are no longer required (because, the chain is always going forward). This works well in practice, so I'll suggest to stick to this :+1:

Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: I did all those changes... but note that a regular uninterrupted sync on non-mainnet will be slower due to the inserts.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 26]
```diff
@@ -505,25 +511,49 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
+
+        -- | Like 'forM_', except runs the second action for the last element as
+        -- well (in addition to the first action).
+        forML_ :: (Monad m)
+            => NonEmpty a
+            -> (a -> m b) -- ^ action to run for all elements
+            -> (a -> m c) -- ^ action to run for the last element
+            -> m ()
+        {-# INLINE forML_ #-}
+        forML_ ne a1 a2 = go (NE.toList ne)
```
Comment (jonathanknowles) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: **Suggestion:** replace this abstraction with something simpler.

**Justification:**

It seems to me that very short and cryptic names are generally reserved for functions that are very general in nature, such as `forM`, or `scanM` and so on. Since we tend to reuse these general functions a great deal, it doesn't matter that they have short names: the names become part of the lexicon that everyone gets used to over time. And because we have to read them so frequently, being short has an advantage.

But this function is specialized to a single use case. Having a cryptic name means that the reader has to go to the definition of the function to figure out what it's doing.

The overall design also seems a bit brittle: if we need to change the way we record block headers (for example), then it's likely we'll need to replace `forML_` with something else entirely.

**Proposal:**

Why not write something like this, instead:
```hs
forward latestGarbageCollectionEpochRef blocks _ = do
    atomically $ do
        recordPoolCertificates blocks
        recordBlockHeaders blocks
    pure Continue

```
And then just let `recordPoolCertificates` and `recordBlockHeaders` decide what they want to do with the blocks they are given?

So we could have something like this:
```hs
recordPoolCertificates blocks = do
    forM_ blocks $ \case
        BlockByron _ ->
            -- Do nothing, as pools did not exist in the Byron era.
            pure ()
        BlockShelley blk ->
            -- Do stuff.

recordBlockHeaders blocks =
    case NE.last blocks of
        BlockByron blk ->
            putHeader (toByronBlockHeader gp blk)
        BlockShelley blk ->
            putHeader (toShelleyBlockHeader getGenesisBlockHash blk)
```
Then there is no need to invent an extra combinator.

What do you think?

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 27]
```diff
@@ -554,6 +557,18 @@ newDBLayer trace fp timeInterpreter = do
...
+        putHeader point =
+                let record = mkBlockHeader point
+                    key = TH.blockHeight record
+                in repsert (BlockHeaderKey key) record
+
+        listHeaders k = do
+            reverse . fmap (fromBlockHeaders . entityVal) <$> selectList [ ]
+                [ Desc BlockHeight
+                , LimitTo k
+                ]
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs:606]: **Request:** add a very simple property test for `listHeaders` that relates it to the `putHeader` and `dropHeaders` functions.

**Justification:**

By adding a property, we can check that both the SQLite implementation and the model implementation behave in the same way (especially if someone else changes this code in future).

In particular, it seems that the ordering is important here. We'd presumably like to know that both the model and the SQLite implementation return the most-recently-added items first.

(We'd presumably also like to know that both implementations respect the `k` parameter.)

For inspiration, see the existing properties in `lib/core/test/unit/Cardano/Pool/DB/Properties.hs`.

**Review by jonathanknowles — CHANGES_REQUESTED** [review]
Hi @hasufell 

Thanks for all your changes after the previous review.

I still have one request and one suggestion:

- **Request**: Add at least a simple property test for the `listBlockHeaders` function.
  See [here](https://github.com/input-output-hk/cardano-wallet/pull/2138#discussion_r489298298) for more details.

- **Suggestion**: Simplify the `forML_` abstraction.
  See [here](https://github.com/input-output-hk/cardano-wallet/pull/2138#discussion_r489294895) for more details.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 26 above)
Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: As I already explained... I think it's best to explicitly avoid traversing the list twice. This is a hot loop.

> But this function is specialized to a single use case. Having a cryptic name means that the reader has to go to the definition of the function to figure out what it's doing.

Yes it is. I checked if there's something similar already, but I couldn't find it. If you want to suggest a different name, please do so.

> The overall design also seems a bit brittle: if we need to change the way we record block headers (for example), then it's likely we'll need to replace forML_ with something else entirely.

I don't think this is a problem. If the code changes in the future, this will be a simple change.

File: lib/core/src/Cardano/Pool/DB.hs [hunk 28]
```diff
@@ -223,6 +223,19 @@ data DBLayer m = forall stm. (MonadFail stm, MonadIO stm) => DBLayer
...
+        -> stm ()
+        -- ^ Add a block header
+
+    , listHeaders
+        :: Int -- ^ limit
+        -> stm [BlockHeader]
+        -- ^ List headers, usually stored during syncing
+
+    , dropHeaders
+        :: stm ()
```
Comment (KtorZ) [inline lib/core/src/Cardano/Pool/DB.hs]: May I suggest calling this one `prune` for consistency with the other DBLayer. They have exactly the same purpose.

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 29]
```diff
@@ -554,6 +557,18 @@ newDBLayer trace fp timeInterpreter = do
...
+
+        dropHeaders = deleteWhere @_ @_ @TH.BlockHeader []
```
Comment (KtorZ) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]: That sounds a little drastic no :) ? It seems like there's a conflict regarding the goal of such function. To me, the dropHeaders / prune function should remove block headers that are no-longer needed (i.e., those that are older than `k`). 

What is the rationale of the current implementation above?

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 30]
```diff
@@ -837,6 +852,23 @@ fromPoolProduction (PoolProduction pool slot headerH parentH height) =
...
+    -> TH.BlockHeader
+mkBlockHeader block = TH.BlockHeader
+    { blockSlot = view #slotNo block
+    , blockHeaderHash = BlockId (headerHash block)
+    , blockParentHash = BlockId (parentHeaderHash block)
+    , TH.blockHeight = getQuantity (blockHeight block)
+    }
+
+fromBlockHeaders :: TH.BlockHeader -> BlockHeader
+fromBlockHeaders TH.BlockHeader { .. } =
```
Comment (KtorZ) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]: Note that, whenever possible, we avoid RecordWildCards and prefer instead NamedFieldPuns. RecordWildCards create implicit let bindings in scope that can be hard to follow, especially in large functions. I don't think it's a problem here because the function is straightforward to follow; yet I'd still favor NamedFieldPuns approach for consistency with the rest of the codebase :+1:

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 31]
```diff
@@ -494,7 +498,9 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
     mkLatestGarbageCollectionEpochRef = newIORef minBound
 
     initCursor :: IO [BlockHeader]
-    initCursor = atomically $ readPoolProductionCursor (max 100 k)
```
Comment (KtorZ) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs:503]: I think that the `readPoolProductionCursor` is made obsolete by this PR. So I'd be good to clean it up as well ?

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 32]
```diff
@@ -505,25 +511,49 @@ monitorStakePools tr gp nl db@DBLayer{..} = do
...
+            => NonEmpty a
+            -> (a -> m b) -- ^ action to run for all elements
+            -> (a -> m c) -- ^ action to run for the last element
+            -> m ()
+        {-# INLINE forML_ #-}
+        forML_ ne a1 a2 = go (NE.toList ne)
+          where
+            go []  = pure ()
+            go [x] = a1 x >> a2 x >> go []
+            go (x:xs) = a1 x >> go xs
```
Comment (KtorZ) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs:556]: :+1:

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 26 above)
Comment (KtorZ) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]: Not a huge fan of the name `forML_` which is a bit cryptic, but I do agree that traversing the list one once is essential here (that's about 4M elements on mainnet!) 

Perhaps resorting to a slightly more transparent name could help make this clearer. A suggestion: `forAllAndLastM`?

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs (hunk 27 above)
Comment (hasufell) [reply lib/core/src/Cardano/Pool/DB/Sqlite.hs:606]: > In particular, it seems that the ordering is important here. We'd presumably like to know that both the model and the SQLite implementation return the most-recently-added items first.

They return the oldest item first... it's a bit confusing, but the intersection finding function expects them that way.

Comment (hasufell) [reply lib/core/src/Cardano/Pool/DB/Sqlite.hs:606]: This is the test:

```hs
prop_putHeaderListHeader
    :: DBLayer IO
    -> [BlockHeader]
    -> Positive Int
    -> Property
prop_putHeaderListHeader DBLayer{..} headers (Positive k) =
    monadicIO (setup >> prop)
  where
    sortedHeaders = sortBy (\a b -> compare (blockHeight a) (blockHeight b))
        . L.nubBy (\a b -> (blockHeight a) == (blockHeight b)) . nub $ headers
    expected = reverse . (if k == 0 then id else take k) . reverse $ sortedHeaders
    setup = run $ atomically cleanDB
    prop = do
        void $ run $ atomically $ forM sortedHeaders putHeader
        lHeaders <- run $ atomically $ listHeaders k
        monitor $ counterexample $ unlines
            [ "Read from DB: " <> show lHeaders
            , "Expected: " <> show expected
            , "Input: " <> show sortedHeaders
            , "k: " <> show k]
        monitor $ classify (null lHeaders) "Empty distributions"
        assert (lHeaders == expected)
        assert (strictlyIncreasing . fmap blockHeight $ lHeaders)

    strictlyIncreasing :: Ord a => [a] -> Bool
    strictlyIncreasing [] = True
    strictlyIncreasing [_] = True
    strictlyIncreasing (x:y:xs) = (x < y) && strictlyIncreasing (y:xs)
```

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 33]
```diff
@@ -1284,6 +1294,38 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
...
+-- | read . put == pure
+prop_putHeaderListHeader
+    :: DBLayer IO
+    -> [BlockHeader]
+    -> Positive Int
+    -> Property
+prop_putHeaderListHeader DBLayer{..} headers (Positive k) =
+    monadicIO (setup >> prop)
+  where
+    sortedHeaders = sortBy (\a b -> compare (blockHeight a) (blockHeight b))
```
Comment (hasufell) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: The generator can't really simulate how we get blocks from the node, so we need to do some deduplicaton and sorting. Pesky.

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 34]
```diff
@@ -1284,6 +1294,38 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
...
+        . L.nubBy (\a b -> (blockHeight a) == (blockHeight b)) . nub $ headers
+    expected = reverse . (if k == 0 then id else take k) . reverse $ sortedHeaders
```
Comment (hasufell) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: This simulates the limiting of the results to the latest k elements, while still retaining order of oldest block first.

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 35]
```diff
@@ -1284,6 +1294,38 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
...
+        void $ run $ atomically $ forM sortedHeaders putHeader
+        lHeaders <- run $ atomically $ listHeaders k
+        monitor $ counterexample $ unlines
+            [ "Read from DB: " <> show lHeaders
+            , "Expected: " <> show expected
+            , "Input: " <> show sortedHeaders
+            , "k: " <> show k]
+        monitor $ classify (null lHeaders) "Empty distributions"
+        assert (lHeaders == expected)
+        assert (strictlyIncreasing . fmap blockHeight $ lHeaders)
```
Comment (hasufell) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: I guess this property is kinda implicit in the fact that `expected` is already sorted that way, but I think it's fine to have it explicitly.

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs (hunk 31 above)
Comment (hasufell) [reply lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs:503]: It is used in Jormungandr and I haven't touched that code yet.

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs (hunk 29 above)
Comment (hasufell) [reply lib/core/src/Cardano/Pool/DB/Sqlite.hs]: I currently have no plans implementing prune. I think the size of the header table is fairly ok, is it not? `dropHeaders` was used previously in the implementation where I kept only one block header in total in the table. This is not the case anymore, so I could remove it altogether.

File: lib/core/test/unit/Cardano/Wallet/Gen.hs [hunk 36]
```diff
@@ -153,9 +153,12 @@ genBlockHeader sl = do
...
         genHash = elements
-            [ Hash "BLOCK01"
-            , Hash "BLOCK02"
-            , Hash "BLOCK03"
+            [ Hash $ unsafeFromHex
+                "aac1308b9868af89c396b08ff6f3cfea8e0859c94d1b3bc834baeaaff8645448"
+            , Hash $ unsafeFromHex
+                "d93b27cc7bb6fd2fe6ee42de5328c13606bb714a78475a41335207d2afd6026e"
+            , Hash $ unsafeFromHex
+                "63b8828e2eadc3f14b9b691fa9df76139a9c9b13a12ec862b324cc5a88f9fcc5"
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Wallet/Gen.hs:160]: Hi @hasufell

Could you explain your reasoning for using long hex values here?

AFAIK, the motivation for using short, human-readable strings like "BLOCK0", "BLOCK1" and so on is to make counterexamples more readable. With short strings, we can more easily see the structure of nested values.

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 37]
```diff
@@ -1284,6 +1294,38 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
...
+
+    strictlyIncreasing :: Ord a => [a] -> Bool
+    strictlyIncreasing [] = True
+    strictlyIncreasing [_] = True
+    strictlyIncreasing (x:y:xs) = let !b = (x < y) in b && strictlyIncreasing (y:xs)
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: **Request**: please stick to the [line length limit](https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards#limit-line-length-to-80-characters) if you can!

**Suggestion**: this function could also be expressed as:
```suggestion
    strictlyIncreasing xs = all (uncurry (<)) (xs `zip` tail xs)
```

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 38]
```diff
@@ -1284,6 +1294,38 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
...
+prop_putHeaderListHeader
+    :: DBLayer IO
+    -> [BlockHeader]
+    -> Positive Int
+    -> Property
+prop_putHeaderListHeader DBLayer{..} headers (Positive k) =
+    monadicIO (setup >> prop)
+  where
+    sortedHeaders = sortBy (\a b -> compare (blockHeight a) (blockHeight b))
+        . L.nubBy (\a b -> (blockHeight a) == (blockHeight b)) . nub $ headers
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: Suggestion: Use [`nubSortOn`](https://hackage.haskell.org/package/extra-1.7.8/docs/Data-List-Extra.html#v:nubSortOn) here:

```suggestion
    sortedHeaders = nubSortOn blockHeight . nub $ headers
```

Also, is the second `nub` actually necessary?

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs (hunk 34 above)
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: I don't think we need the zero-value test here, as we have already specified that k is `Positive` (which QuickCheck [guarantees as being greater than `0`](http://hackage.haskell.org/package/QuickCheck-2.14.1/docs/Test-QuickCheck-Modifiers.html#t:Positive)).

But even if we did encounter a value of `0`, shouldn't we then just take `0` elements?

I would also be inclined to change the `Positive` to `NonNegative`, as we probably do want to test what happens when `k == 0`.

```suggestion
    expected = reverse . take k . reverse $ sortedHeaders
```

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs (hunk 35 above)
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: **Suggestion**: use `assertWith` here, since we have more than one assertion.

**Justification**: when we encounter a failure, it's good to know _which_ assertion failed.

So something like:

```suggestion
        assertWith "read back the headers we expected"
            (lHeaders == expected)
        assertWith "headers are increasing in block height"
            (strictlyIncreasing . fmap blockHeight $ lHeaders)
```

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 39]
```diff
@@ -1334,3 +1376,7 @@ testCertificatePublicationTimes =
     | sn <- [0 ..  ]
     , ii <- [0 .. 3]
     ]
+
+instance Arbitrary BlockHeader where
+    arbitrary = arbitrary >>= genBlockHeader
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: Suggestion: use `genSlotNo` here:
```suggestion
    arbitrary = genSlotNo >>= genBlockHeader
```

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 40]
```diff
@@ -554,6 +558,17 @@ newDBLayer trace fp timeInterpreter = do
                 let cpt = CertificatePublicationTime {slotNo, slotInternalIndex}
                 pure (cpt, cert)
 
+        putHeader point =
+                let record = mkBlockHeader point
+                    key = TH.blockHeight record
+                in repsert (BlockHeaderKey key) record
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]: **Request**: use 4-space indents.

```suggestion
        putHeader point =
            let record = mkBlockHeader point
                key = TH.blockHeight record
            in repsert (BlockHeaderKey key) record
```

File: lib/core/src/Cardano/Pool/DB/Model.hs [hunk 41]
```diff
@@ -416,6 +422,15 @@ mRemoveRetiredPools epoch = do
...
 
+mPutHeader :: BlockHeader -> ModelOp ()
+mPutHeader header = modify #blockHeaders (header :)
+
+mListHeaders :: Int -> ModelOp [BlockHeader]
+mListHeaders k
+    | k > 0 = reverse . take k <$> get #blockHeaders
+    | otherwise = reverse <$> get #blockHeaders
+
+
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Model.hs]:
```suggestion

```
https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards#use-only-a-single-blank-line-between-top-level-definitions

File: lib/core/src/Cardano/Pool/DB/Model.hs [hunk 42]
```diff
@@ -416,6 +422,15 @@ mRemoveRetiredPools epoch = do
     mRemovePools (view #poolId <$> certificates)
     pure certificates
 
+mPutHeader :: BlockHeader -> ModelOp ()
+mPutHeader header = modify #blockHeaders (header :)
+
+mListHeaders :: Int -> ModelOp [BlockHeader]
+mListHeaders k
+    | k > 0 = reverse . take k <$> get #blockHeaders
+    | otherwise = reverse <$> get #blockHeaders
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Model.hs:431]: Hi @hasufell, is there a good reason for returning the whole list when `k == 0`?

If not, I would be inclined to either remove this special case, or instead write something like:
```hs
mListHeaders :: Int -> ModelOp [BlockHeader]
mListHeaders k
    | k > 0 = reverse . take k <$> get #blockHeaders
    | otherwise = pure []
```

It also seems that this behaviour is different from the SQLite implementation, which just returns 0 rows if `k` is zero. (Though please correct me if I'm wrong here!)

We ideally want the model and SQLite implementations to behave in exactly the same way. (At some point in the future, we'll probably add QSM-style tests that verify this, in the same way we currently do for the wallet DB.)

**Review by jonathanknowles — CHANGES_REQUESTED** [review]
Hi @hasufell 

Many thanks for adding the property test!

I still have a few requests and suggestions. (See comments.)

Cheers!

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 43]
```diff
@@ -1284,6 +1294,38 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
     certificateSequences = getSinglePoolSequences mpcs
     poolCount = length certificateSequences
 
+
+-- | read . put == pure
+prop_putHeaderListHeader
+    :: DBLayer IO
+    -> [BlockHeader]
+    -> Positive Int
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: I would be inclined to change this to `NonNegative`.

Justification: the `listHeaders` function is not just defined on the set of positive values. In particular, it also has defined behaviour when `k == 0`.

File: lib/core/test/unit/Cardano/Wallet/Gen.hs (hunk 36 above)
Comment (hasufell) [reply lib/core/test/unit/Cardano/Wallet/Gen.hs:160]: > AFAIK, the motivation for using short, human-readable strings like "BLOCK0", "BLOCK1" and so on is to make counterexamples more readable.

It failed serialisation/deserialisation.

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs (hunk 34 above)
Comment (hasufell) [reply lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: > But even if we did encounter a value of 0, shouldn't we then just take 0 elements?

Nope, in that case we should take **all** elements. That's how `LimitTo` from persistent works. This emulates it. And as such, we want the 0-case.

File: lib/core/src/Cardano/Pool/DB/Model.hs (hunk 42 above)
Comment (hasufell) [reply lib/core/src/Cardano/Pool/DB/Model.hs:431]: > It also seems that this behaviour is different from the SQLite implementation, which just returns 0 rows if k is zero. (Though please correct me if I'm wrong here!)

I returns all elements if k is 0.

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs (hunk 37 above)
Comment (hasufell) [reply lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: I find this far less readable.

Comment (jonathanknowles) [reply lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: That was indeed just a suggestion.

But I would still appreciate it if you could fix the line length issue. This would work:
```suggestion
    strictlyIncreasing [] = True
    strictlyIncreasing [_] = True
    strictlyIncreasing (x:y:xs) =
        let !b = (x < y) in b && strictlyIncreasing (y:xs)
```

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs (hunk 34 above)
Comment (jonathanknowles) [reply lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: > Nope, in that case we should take all elements. That's how `LimitTo` from persistent works. This emulates it. And as such, we want the 0-case.

Is this documented anywhere?

I couldn't find any mention of this in [the Haddock documentation for `LimitTo`](https://hackage.haskell.org/package/persistent-2.10.5.2/docs/Database-Persist-Types.html#t:SelectOpt).

If this is the case, then we should definitely add a comment in the interface for `DBLayer.listHeaders`, to let callers know this is what they should expect.

File: lib/core/src/Cardano/Pool/DB/Model.hs (hunk 42 above)
Comment (jonathanknowles) [reply lib/core/src/Cardano/Pool/DB/Model.hs:431]: > > It also seems that this behaviour is different from the SQLite implementation, which just returns 0 rows if k is zero. (Though please correct me if I'm wrong here!)
> 
> I returns all elements if k is 0.

Is this documented anywhere?

I couldn't find any mention of this in [the Haddock documentation for `LimitTo`](https://hackage.haskell.org/package/persistent-2.10.5.2/docs/Database-Persist-Types.html#t:SelectOpt).

If this is the case, then we should definitely add a comment in the interface for `DBLayer.listHeaders`, to let callers know this is what they should expect.

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs (hunk 34 above)
Comment (hasufell) [reply lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: I don't know, but that's what the implementation does:

https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist.hs#L389-L398

https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist/Sql/Orphan/PersistQuery.hs#L396-L409

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs (hunk 37 above)
Comment (hasufell) [reply lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: Done

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs (hunk 34 above)
Comment (jonathanknowles) [reply lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: > I don't know, but that's what the implementation does:

Thanks for confirming.

It's very surprising that this isn't documented anywhere! (I would have thought that the [`LimitTo` constructor](https://hackage.haskell.org/package/persistent-2.10.5.2/docs/Database-Persist-Types.html#t:SelectOpt) would be an excellent place to put this documentation.)

In any case, I think we should do one of the following:

1. Adjust the SQLite implementation of `listHeaders` to check for `limit <= 0` and then return `[]`.
2. Document the special significance of `limit <= 0` in the interface to `listHeaders`.

My preference would be for option 1, as I'm not a fan of using magic values. IMO, it should _never_ be the case that _reducing_ a limit causes a function to return _more_ values. This breaks the principle of monotonicity.

If OTOH we really need to support the case where caller wants all values, perhaps the limit can be specified as `Maybe Int`, or by using a sum type.

File: lib/core/src/Cardano/Pool/DB.hs [hunk 44]
```diff
@@ -223,6 +224,17 @@ data DBLayer m = forall stm. (MonadFail stm, MonadIO stm) => DBLayer
...
+    , putHeader
+        :: BlockHeader
+        -> stm ()
+        -- ^ Add a block header
+
+    , listHeaders
+        :: Int -- ^ limit
+        -> stm [BlockHeader]
+        -- ^ List headers, usually stored during syncing.
+        -- Returns all headers if limit is <= 0.
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB.hs:236]: :+1:

File: lib/core/src/Cardano/Pool/DB.hs [hunk 45]
```diff
@@ -107,6 +107,7 @@ data DBLayer m = forall stm. (MonadFail stm, MonadIO stm) => DBLayer
         -- be the last element in the list.
         --
         -- This is useful for the @NetworkLayer@ to know how far we have synced.
+        -- Returns all headers if limit is <= 0.
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB.hs:110]: :+1:

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 46]
```diff
@@ -1284,6 +1293,56 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
     certificateSequences = getSinglePoolSequences mpcs
     poolCount = length certificateSequences
 
+
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]:
```suggestion
```

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 47]
```diff
@@ -1284,6 +1293,56 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
...
+    :: DBLayer IO
+    -> [BlockHeader]
+    -> NonNegative Int
+    -> Property
+prop_putHeaderListHeader DBLayer{..} headers (NonNegative k) =
+    monadicIO (setup >> prop)
+  where
+    -- The generator can't really simulate how we get blocks from the node,
+    -- so we need to do some deduplicaton and sorting.
+    sortedHeaders = nubSortOn blockHeight headers
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs:1307]: :+1: (for use of `nubSortOn`: this is much clearer)

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 48]
```diff
@@ -1284,6 +1293,56 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
...
+
+    limitTo
+        :: Int
+        -> [a]  -- ^ input list, sorted in ascending order
+        -> [a]  -- ^ output sorted in ascending order, but limited
+                --   to last n elements
+    limitTo n
+        | n <= 0 = id
+        -- this emulates persistent [LimitTo n, Desc ...]
+        | otherwise = reverse . take n . reverse
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs:1342]: :+1:

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 49]
```diff
@@ -1284,6 +1293,56 @@ prop_MultiPoolCertificateSequence_coverage mpcs = checkCoverage
...
+
+
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]:
```suggestion
```

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 50]
```diff
@@ -702,3 +732,22 @@ instance ToText StakePoolLog where
             , "back to it in about "
             , pretty (fixedF 1 (toRational delay / 1000000)), "s"
             ]
+
+
```
Comment (jonathanknowles) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]:
```suggestion

```

File: lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs [hunk 51]
```diff
@@ -702,3 +732,22 @@ instance ToText StakePoolLog where
...
+--
+lastByronBlock :: BlockHeader
+lastByronBlock = BlockHeader
+    (SlotNo 4492799)
+    (Quantity 4490510)
+    (Hash $ unsafeFromHex
+        "f8084c61b6a238acec985b59310b6ecec49c0ab8352249afd7268da5cff2a457")
+    (Hash $ unsafeFromHex
+        "aa83acbf5904c0edfe4d79b3689d3d00fcfc553cf360fd2229b98d464c28e9de")
+
```
Comment (jonathanknowles) [inline lib/shelley/src/Cardano/Wallet/Shelley/Pools.hs]:
```suggestion

```

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 52]
```diff
@@ -131,8 +131,11 @@ import System.FilePath
 import System.Random
     ( newStdGen )
 
-import Cardano.Pool.DB.Sqlite.TH
+import Cardano.Pool.DB.Sqlite.TH hiding
+    ( BlockHeader, blockHeight )
 
+
```
Comment (jonathanknowles) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs]:
```suggestion
```

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs [hunk 53]
```diff
@@ -1334,3 +1393,7 @@ testCertificatePublicationTimes =
     | sn <- [0 ..  ]
     , ii <- [0 .. 3]
     ]
+
+instance Arbitrary BlockHeader where
+    arbitrary = genSlotNo >>= genBlockHeader
+
```
Comment (jonathanknowles) [inline lib/core/test/unit/Cardano/Pool/DB/Properties.hs]:
```suggestion
```

File: lib/core/test/unit/Cardano/Pool/DB/Properties.hs (hunk 34 above)
Comment (hasufell) [reply lib/core/test/unit/Cardano/Pool/DB/Properties.hs]: I'd propose creating a separate ticket/PR for this. I added documentation about this behavior though.

**Review by jonathanknowles — APPROVED** [review]
Hi @hasufell 

Thanks for making all the changes.

As for [`LimitTo`](https://hackage.haskell.org/package/persistent-2.10.5.2/docs/Database-Persist-Types.html#t:SelectOpt), I'm still rather shocked that specifying `LimitTo 0` causes `persistent` to issue a query that selects **_all_** rows. IMO, this breaks the principle of monotonicity, in that _decreasing_ a limit should never lead to an _increase_ in the size of the result. (I'm somewhat inclined to file a bug in `persistent` for this surprising behaviour.)

I think it's fine to document the special behaviour for `limit <= 0` in the interface for `DBLayer.listHeaders` for now (as you have done), though I think we should probably try to fix this at some stage so that it really does return `[]`. (Perhaps using `Maybe Int` would work here if we really want to support fetching everything.)

I've approved this PR, but there's still one more thing:

This patch inserts several extraneous carriage returns in a few places. Would you be able to remove the double spaces before merging? I've highlighted these in the comments attached to this review, so you should be able to just hit "apply suggestion" wherever necessary. Thanks! (See [coding standards](https://github.com/input-output-hk/cardano-wallet/wiki/Coding-Standards#use-only-a-single-blank-line-between-top-level-definitions).)

**Comment by hasufell** [comment]
bors try

**Comment by hasufell** [comment]
bors try

**Comment by hasufell** [comment]
bors try

**Comment by KtorZ** [comment]
bors try

**Comment by hasufell** [comment]
It seems the wallet recurses on the intersection and then eventually overloads/kills the node:

<details><summary>partial test log</summary>
<p>

```
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Looking for an intersection with the node's local chain with: f5d4622d<-[9f242fa9-0#0], 8392db62<-[ce07851c-104#84], eb7c6c2f<-[a9b6b9a8-128#87], 44507ac3<-[78832858-208#97], 8b75b166<-[76d8c452-288#107], f65ed39f<-[1063a07a-360#116], 72d95197<-[6bb1e260-376#118], 6bb1e260<-[234647a4-384#119], 234647a4<-[a3a5b7b7-392#120], a3a5b7b7<-[c566bb13-400#121], c566bb13<-[fba1fad5-408#122], fba1fad5<-[799d8dc4-416#123], 799d8dc4<-[853cc2cb-424#124], 853cc2cb<-[75f7e043-432#125], 75f7e043<-[3e60b67d-440#126], 3e60b67d<-[bcc77c19-448#127], bcc77c19<-[1fbf377e-456#128], 1fbf377e<-[60cbca7b-464#129], 60cbca7b<-[c9761b17-472#130], c9761b17<-[6a3fa324-480#131], 6a3fa324<-[1a82b1e5-482#132], 1a82b1e5<-[4320c116-486#133], 4320c116<-[5b8e434e-488#134], 5b8e434e<-[23045d77-493#135], c499f26d<-[c83a3353-502#141], c83a3353<-[a04475ce-504#142], a04475ce<-[6783a1de-506#143], 6783a1de<-[29b97b1d-510#144], 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1838][0m [2020-09-22 15:18:47.27 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Recv MsgAcceptVersion NodeToClientV_3 (TInt 764824073)
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Intersection found: 29b97b1d
[35m[cardano-wallet.network:Notice:1576][0m [2020-09-22 15:18:47.27 UTC] Destroying cursor connection at ThreadId 1838
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Rolling back to 510
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Monitoring stake pools. Currently at 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1850][0m [2020-09-22 15:18:47.27 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Send MsgProposeVersions (fromList [(NodeToClientV_3,TInt 764824073)])
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Looking for an intersection with the node's local chain with: f5d4622d<-[9f242fa9-0#0], 8392db62<-[ce07851c-104#84], eb7c6c2f<-[a9b6b9a8-128#87], 44507ac3<-[78832858-208#97], 8b75b166<-[76d8c452-288#107], f65ed39f<-[1063a07a-360#116], 72d95197<-[6bb1e260-376#118], 6bb1e260<-[234647a4-384#119], 234647a4<-[a3a5b7b7-392#120], a3a5b7b7<-[c566bb13-400#121], c566bb13<-[fba1fad5-408#122], fba1fad5<-[799d8dc4-416#123], 799d8dc4<-[853cc2cb-424#124], 853cc2cb<-[75f7e043-432#125], 75f7e043<-[3e60b67d-440#126], 3e60b67d<-[bcc77c19-448#127], bcc77c19<-[1fbf377e-456#128], 1fbf377e<-[60cbca7b-464#129], 60cbca7b<-[c9761b17-472#130], c9761b17<-[6a3fa324-480#131], 6a3fa324<-[1a82b1e5-482#132], 1a82b1e5<-[4320c116-486#133], 4320c116<-[5b8e434e-488#134], 5b8e434e<-[23045d77-493#135], c499f26d<-[c83a3353-502#141], c83a3353<-[a04475ce-504#142], a04475ce<-[6783a1de-506#143], 6783a1de<-[29b97b1d-510#144], 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1850][0m [2020-09-22 15:18:47.27 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Recv MsgAcceptVersion NodeToClientV_3 (TInt 764824073)
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Intersection found: 29b97b1d
[35m[cardano-wallet.network:Notice:1576][0m [2020-09-22 15:18:47.27 UTC] Destroying cursor connection at ThreadId 1850
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Rolling back to 510
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Monitoring stake pools. Currently at 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1863][0m [2020-09-22 15:18:47.27 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Send MsgProposeVersions (fromList [(NodeToClientV_3,TInt 764824073)])
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Looking for an intersection with the node's local chain with: f5d4622d<-[9f242fa9-0#0], 8392db62<-[ce07851c-104#84], eb7c6c2f<-[a9b6b9a8-128#87], 44507ac3<-[78832858-208#97], 8b75b166<-[76d8c452-288#107], f65ed39f<-[1063a07a-360#116], 72d95197<-[6bb1e260-376#118], 6bb1e260<-[234647a4-384#119], 234647a4<-[a3a5b7b7-392#120], a3a5b7b7<-[c566bb13-400#121], c566bb13<-[fba1fad5-408#122], fba1fad5<-[799d8dc4-416#123], 799d8dc4<-[853cc2cb-424#124], 853cc2cb<-[75f7e043-432#125], 75f7e043<-[3e60b67d-440#126], 3e60b67d<-[bcc77c19-448#127], bcc77c19<-[1fbf377e-456#128], 1fbf377e<-[60cbca7b-464#129], 60cbca7b<-[c9761b17-472#130], c9761b17<-[6a3fa324-480#131], 6a3fa324<-[1a82b1e5-482#132], 1a82b1e5<-[4320c116-486#133], 4320c116<-[5b8e434e-488#134], 5b8e434e<-[23045d77-493#135], c499f26d<-[c83a3353-502#141], c83a3353<-[a04475ce-504#142], a04475ce<-[6783a1de-506#143], 6783a1de<-[29b97b1d-510#144], 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1863][0m [2020-09-22 15:18:47.27 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Recv MsgAcceptVersion NodeToClientV_3 (TInt 764824073)
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Intersection found: 29b97b1d
[35m[cardano-wallet.network:Notice:1576][0m [2020-09-22 15:18:47.27 UTC] Destroying cursor connection at ThreadId 1863
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Rolling back to 510
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.27 UTC] Monitoring stake pools. Currently at 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1875][0m [2020-09-22 15:18:47.28 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Send MsgProposeVersions (fromList [(NodeToClientV_3,TInt 764824073)])
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Looking for an intersection with the node's local chain with: f5d4622d<-[9f242fa9-0#0], 8392db62<-[ce07851c-104#84], eb7c6c2f<-[a9b6b9a8-128#87], 44507ac3<-[78832858-208#97], 8b75b166<-[76d8c452-288#107], f65ed39f<-[1063a07a-360#116], 72d95197<-[6bb1e260-376#118], 6bb1e260<-[234647a4-384#119], 234647a4<-[a3a5b7b7-392#120], a3a5b7b7<-[c566bb13-400#121], c566bb13<-[fba1fad5-408#122], fba1fad5<-[799d8dc4-416#123], 799d8dc4<-[853cc2cb-424#124], 853cc2cb<-[75f7e043-432#125], 75f7e043<-[3e60b67d-440#126], 3e60b67d<-[bcc77c19-448#127], bcc77c19<-[1fbf377e-456#128], 1fbf377e<-[60cbca7b-464#129], 60cbca7b<-[c9761b17-472#130], c9761b17<-[6a3fa324-480#131], 6a3fa324<-[1a82b1e5-482#132], 1a82b1e5<-[4320c116-486#133], 4320c116<-[5b8e434e-488#134], 5b8e434e<-[23045d77-493#135], c499f26d<-[c83a3353-502#141], c83a3353<-[a04475ce-504#142], a04475ce<-[6783a1de-506#143], 6783a1de<-[29b97b1d-510#144], 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1875][0m [2020-09-22 15:18:47.28 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Recv MsgAcceptVersion NodeToClientV_3 (TInt 764824073)
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Intersection found: 29b97b1d
[35m[cardano-wallet.network:Notice:1576][0m [2020-09-22 15:18:47.28 UTC] Destroying cursor connection at ThreadId 1875
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Rolling back to 510
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Monitoring stake pools. Currently at 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1887][0m [2020-09-22 15:18:47.28 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Send MsgProposeVersions (fromList [(NodeToClientV_3,TInt 764824073)])
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Looking for an intersection with the node's local chain with: f5d4622d<-[9f242fa9-0#0], 8392db62<-[ce07851c-104#84], eb7c6c2f<-[a9b6b9a8-128#87], 44507ac3<-[78832858-208#97], 8b75b166<-[76d8c452-288#107], f65ed39f<-[1063a07a-360#116], 72d95197<-[6bb1e260-376#118], 6bb1e260<-[234647a4-384#119], 234647a4<-[a3a5b7b7-392#120], a3a5b7b7<-[c566bb13-400#121], c566bb13<-[fba1fad5-408#122], fba1fad5<-[799d8dc4-416#123], 799d8dc4<-[853cc2cb-424#124], 853cc2cb<-[75f7e043-432#125], 75f7e043<-[3e60b67d-440#126], 3e60b67d<-[bcc77c19-448#127], bcc77c19<-[1fbf377e-456#128], 1fbf377e<-[60cbca7b-464#129], 60cbca7b<-[c9761b17-472#130], c9761b17<-[6a3fa324-480#131], 6a3fa324<-[1a82b1e5-482#132], 1a82b1e5<-[4320c116-486#133], 4320c116<-[5b8e434e-488#134], 5b8e434e<-[23045d77-493#135], c499f26d<-[c83a3353-502#141], c83a3353<-[a04475ce-504#142], a04475ce<-[6783a1de-506#143], 6783a1de<-[29b97b1d-510#144], 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1887][0m [2020-09-22 15:18:47.28 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Recv MsgAcceptVersion NodeToClientV_3 (TInt 764824073)
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Intersection found: 29b97b1d
[35m[cardano-wallet.network:Notice:1576][0m [2020-09-22 15:18:47.28 UTC] Destroying cursor connection at ThreadId 1887
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Rolling back to 510
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Monitoring stake pools. Currently at 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1898][0m [2020-09-22 15:18:47.28 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Send MsgProposeVersions (fromList [(NodeToClientV_3,TInt 764824073)])
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Looking for an intersection with the node's local chain with: f5d4622d<-[9f242fa9-0#0], 8392db62<-[ce07851c-104#84], eb7c6c2f<-[a9b6b9a8-128#87], 44507ac3<-[78832858-208#97], 8b75b166<-[76d8c452-288#107], f65ed39f<-[1063a07a-360#116], 72d95197<-[6bb1e260-376#118], 6bb1e260<-[234647a4-384#119], 234647a4<-[a3a5b7b7-392#120], a3a5b7b7<-[c566bb13-400#121], c566bb13<-[fba1fad5-408#122], fba1fad5<-[799d8dc4-416#123], 799d8dc4<-[853cc2cb-424#124], 853cc2cb<-[75f7e043-432#125], 75f7e043<-[3e60b67d-440#126], 3e60b67d<-[bcc77c19-448#127], bcc77c19<-[1fbf377e-456#128], 1fbf377e<-[60cbca7b-464#129], 60cbca7b<-[c9761b17-472#130], c9761b17<-[6a3fa324-480#131], 6a3fa324<-[1a82b1e5-482#132], 1a82b1e5<-[4320c116-486#133], 4320c116<-[5b8e434e-488#134], 5b8e434e<-[23045d77-493#135], c499f26d<-[c83a3353-502#141], c83a3353<-[a04475ce-504#142], a04475ce<-[6783a1de-506#143], 6783a1de<-[29b97b1d-510#144], 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1898][0m [2020-09-22 15:18:47.28 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Recv MsgAcceptVersion NodeToClientV_3 (TInt 764824073)
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Intersection found: 29b97b1d
[35m[cardano-wallet.network:Notice:1576][0m [2020-09-22 15:18:47.28 UTC] Destroying cursor connection at ThreadId 1898
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Rolling back to 510
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Monitoring stake pools. Currently at 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1910][0m [2020-09-22 15:18:47.28 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Send MsgProposeVersions (fromList [(NodeToClientV_3,TInt 764824073)])
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Looking for an intersection with the node's local chain with: f5d4622d<-[9f242fa9-0#0], 8392db62<-[ce07851c-104#84], eb7c6c2f<-[a9b6b9a8-128#87], 44507ac3<-[78832858-208#97], 8b75b166<-[76d8c452-288#107], f65ed39f<-[1063a07a-360#116], 72d95197<-[6bb1e260-376#118], 6bb1e260<-[234647a4-384#119], 234647a4<-[a3a5b7b7-392#120], a3a5b7b7<-[c566bb13-400#121], c566bb13<-[fba1fad5-408#122], fba1fad5<-[799d8dc4-416#123], 799d8dc4<-[853cc2cb-424#124], 853cc2cb<-[75f7e043-432#125], 75f7e043<-[3e60b67d-440#126], 3e60b67d<-[bcc77c19-448#127], bcc77c19<-[1fbf377e-456#128], 1fbf377e<-[60cbca7b-464#129], 60cbca7b<-[c9761b17-472#130], c9761b17<-[6a3fa324-480#131], 6a3fa324<-[1a82b1e5-482#132], 1a82b1e5<-[4320c116-486#133], 4320c116<-[5b8e434e-488#134], 5b8e434e<-[23045d77-493#135], c499f26d<-[c83a3353-502#141], c83a3353<-[a04475ce-504#142], a04475ce<-[6783a1de-506#143], 6783a1de<-[29b97b1d-510#144], 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1910][0m [2020-09-22 15:18:47.28 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Recv MsgAcceptVersion NodeToClientV_3 (TInt 764824073)
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Intersection found: 29b97b1d
[35m[cardano-wallet.network:Notice:1576][0m [2020-09-22 15:18:47.28 UTC] Destroying cursor connection at ThreadId 1910
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Rolling back to 510
[34m[cardano-wallet.pools-engine:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Monitoring stake pools. Currently at 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1922][0m [2020-09-22 15:18:47.28 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Send MsgProposeVersions (fromList [(NodeToClientV_3,TInt 764824073)])
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.28 UTC] Looking for an intersection with the node's local chain with: f5d4622d<-[9f242fa9-0#0], 8392db62<-[ce07851c-104#84], eb7c6c2f<-[a9b6b9a8-128#87], 44507ac3<-[78832858-208#97], 8b75b166<-[76d8c452-288#107], f65ed39f<-[1063a07a-360#116], 72d95197<-[6bb1e260-376#118], 6bb1e260<-[234647a4-384#119], 234647a4<-[a3a5b7b7-392#120], a3a5b7b7<-[c566bb13-400#121], c566bb13<-[fba1fad5-408#122], fba1fad5<-[799d8dc4-416#123], 799d8dc4<-[853cc2cb-424#124], 853cc2cb<-[75f7e043-432#125], 75f7e043<-[3e60b67d-440#126], 3e60b67d<-[bcc77c19-448#127], bcc77c19<-[1fbf377e-456#128], 1fbf377e<-[60cbca7b-464#129], 60cbca7b<-[c9761b17-472#130], c9761b17<-[6a3fa324-480#131], 6a3fa324<-[1a82b1e5-482#132], 1a82b1e5<-[4320c116-486#133], 4320c116<-[5b8e434e-488#134], 5b8e434e<-[23045d77-493#135], c499f26d<-[c83a3353-502#141], c83a3353<-[a04475ce-504#142], a04475ce<-[6783a1de-506#143], 6783a1de<-[29b97b1d-510#144], 29b97b1d<-[fc9c601d-511#145]
[34m[cardano-wallet.network:Info:1922][0m [2020-09-22 15:18:47.29 UTC] conn::/tmp/test-3ab3557def2f8961/node/node.socket Recv MsgAcceptVersion NodeToClientV_3 (TInt 764824073)
[34m[cardano-wallet.network:Info:1576][0m [2020-09-22 15:18:47.29 UTC] Intersection found: 29b97b1d

```
</p>
</details>

It keeps finding the intersection `29b97b1d` and rolling back to `510`.

The logic of finding headers the old way is:

```hs
        readPoolProductionCursor k = do
            reverse . map (snd . fromPoolProduction . entityVal) <$> selectList
                []
                [Desc PoolProductionSlot, LimitTo k]

```

The new way is:

```hs
        listHeaders k = do
            reverse . fmap (fromBlockHeaders . entityVal) <$> selectList [ ]
                [ Desc BlockHeight
                , LimitTo k
                ]
```

Is the list in the wrong order (because I don't think so)?

**Comment by hasufell** [comment]
I found it:

```hs
        rollbackTo point = do
            -- TODO(ADP-356): What if the conversion blocks or fails?
            --
            -- Missing a rollback would be bad.
            EpochNo epoch <- liftIO $ timeInterpreter (epochOf point)
            deleteWhere [ StakeDistributionEpoch >. fromIntegral epoch ]

            deleteWhere [ PoolProductionSlot >. point ]
            deleteWhere [ PoolRegistrationSlot >. point ]
            deleteWhere [ PoolRetirementSlot >. point ]
            -- TODO: remove dangling metadata no longer attached to a pool
```
This doesn't roll back the headers table...

**Comment by KtorZ** [comment]
> This doesn't roll back the headers table...

Ho :facepalm:

**Comment by hasufell** [comment]
bors try

**Comment by hasufell** [comment]
bors try

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 54]
```diff
@@ -526,6 +529,7 @@ newDBLayer trace fp timeInterpreter = do
             deleteWhere ([] :: [Filter StakeDistribution])
             deleteWhere ([] :: [Filter PoolMetadata])
             deleteWhere ([] :: [Filter PoolMetadataFetchAttempts])
+            deleteWhere ([] :: [Filter TH.BlockHeader])
```
Comment (KtorZ) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs:532]: :ok_hand:

File: lib/core/src/Cardano/Pool/DB/Sqlite.hs [hunk 55]
```diff
@@ -479,6 +481,7 @@ newDBLayer trace fp timeInterpreter = do
             deleteWhere [ PoolProductionSlot >. point ]
             deleteWhere [ PoolRegistrationSlot >. point ]
             deleteWhere [ PoolRetirementSlot >. point ]
+            deleteWhere [ BlockSlot >. point ]
```
Comment (KtorZ) [inline lib/core/src/Cardano/Pool/DB/Sqlite.hs:484]: :ok_hand:

**Review by KtorZ — APPROVED** [review]

**Comment by hasufell** [comment]
I don't know what's going on here...

**Comment by KtorZ** [comment]
bors merge
