### PR TITLE
Fix process cleanup in cardano-wallet-jormungandr:tests:integration

### LINKED ISSUE #877: Jormungandr integration tests leave jormungandr running in background
| Release | Operating System       | Cause |
| ---     | ---                    | ---   |
| next    | Linux | Code  v Configuration v Environment v Human v Unknown |

# Context
 
I think this is integration tests issue related to https://github.com/input-output-hk/cardano-wallet/blob/master/lib/jormungandr/test/integration/Main.hs#L101-L125
(`specWithServer` not cleaning properly, i.e. not killing jormungandr(?))

# Steps to Reproduce

 - Run `stack test cardano-wallet-jormungandr:integration --test-arguments "--match WALLETS_CREATE_03"`
- This runs two tests, one from `API Specification` and one from `CLI specification`, i.e. wallet server with jormungandr is launched twice - one for each test suite.
- After tests are finished -> `ps -ef | grep jorm`

## Expected behavior
No jormungandr instance is running.

## Actual behavior
 There are two instances running. I think that one was spinned for `API spec` the other for `CLI spec`.
```
$ ps -ef | grep jorm
piotr    32169  1557  0 15:32 pts/5    00:00:00 jormungandr --genesis-block test/data/jormungandr/block0.bin --config /tmp/cardano-wallet-jormungandr-dfa3c3bd383bf367/jormungandr-config.yaml --log-level debug --secret test/data/jormungandr/secret.yaml
piotr    32189  1557  0 15:32 pts/5    00:00:00 jormungandr --genesis-block test/data/jormungandr/block0.bin --config /tmp/cardano-wallet-jormungandr-b0c4702ff7dcea47/jormungandr-config.yaml --log-level debug --secret test/data/jormungandr/secret.yaml
```
Doing more integration test runs leaves us with more `jormungandrs` left hanging like this.

---

# Resolution Plan

# PR

| Number   | Base      |
| ---      | ---       |
| #883       | `master` |

# QA

### PR DESCRIPTION
**Pull request by rvl**
Fixes #877.

# Overview

This makes sure that the wallet server thread is cancelled once the integration tests finish. This means it will clean up its jormungandr child process.

### CODE REVIEW

File: lib/jormungandr/test/integration/Main.hs [hunk 1]
```diff
@@ -122,19 +124,21 @@ specWithServer
...
-specWithServer logCfg = beforeAll start . after tearDown
+specWithServer logCfg = beforeAll start . afterAll _cleanup . after tearDown
   where
     start :: IO (Context (Jormungandr 'Testnet))
     start = do
         ctx <- newEmptyMVar
-        pid <- async $ withConfig $ \jmCfg -> do
+        finished <- newEmptyMVar
+        let untilFinished = fmap (either id id) . race (takeMVar finished)
+        pid <- async $ withConfig $ \jmCfg -> untilFinished $ do
```
Comment (KtorZ) [inline lib/jormungandr/test/integration/Main.hs:134]: ~~suggestion:~~

```hs
         let untilFinished = race (takeMVar finished)
         pid <- async $ withConfig $ \jmCfg -> void $ untilFinished $ do
```

?

nevermind.

**Review by KtorZ — APPROVED** [review]

File: lib/jormungandr/test/integration/Main.hs (hunk 1 above)
Comment (rvl) [reply lib/jormungandr/test/integration/Main.hs:134]: I see what you're getting at though. It also bothered me ⇒ #885.
