### PR TITLE
Fix some docker CI issues

### LINKED ISSUE #5001: Remove stopped container leakage
### Why

We want to preserve resources on the builder machine

### What

Add `--rm` flag to https://github.com/cardano-foundation/cardano-wallet/blob/9795369425c8cf45cb34397fb1aba5b6a440a019/run/common/docker/run.sh#L128

### LINKED ISSUE #5011: Isolate docker compose runs
### Why 

We have a lot of failures in the CI due to shared resources. 

### What

Pass a random name to the docker compose runs so the resources will not be shared

### Links 

- [https://docs.docker.com/compose/how-tos/project-name/](https://docs.docker.com/compose/how-tos/project-name/)

### PR DESCRIPTION
**Pull request by paolino**
### Changes 

- Remove leakage by adding --rm to docker run invocations
- Remove resource sharing by adding a name to the docker compose invocations
- Add `-L` to all `nix build` in the CI 

### Issues 

fix #5011 
fix #5001

### CODE REVIEW

File: run/common/docker/run.sh [hunk 1]
```diff
@@ -191,4 +189,4 @@ case "$1" in
         usage  # Display usage information and exit with error
         exit 1
         ;;
-esac
+esac
```
Comment (HeinrichApfelmus) [inline run/common/docker/run.sh]:
```suggestion
esac

```

(newline at end of file)

**Review by HeinrichApfelmus — APPROVED** [review]
🙏

File: run/common/docker/run.sh (hunk 1 above)
Comment (paolino) [reply run/common/docker/run.sh]: Adding an issue for a CI check.There are at least 383 files like this. We will fix them all there. https://github.com/cardano-foundation/cardano-wallet/issues/5014
