### PR TITLE
cabal: Add a flag to enable/disable scrypt

### LINKED ISSUE #2578: cabal build all uses the -msse2 FLAG = Compiling on arm64  - how to reconfigure
# Context

==================== compile uses the -msse2 FLAG =====================
Compiling on arm64  !!!!
using: cabal-install-3.4.0.0
vbox@it4us:~$ cabal --version 
cabal-install version 3.4.0.0
compiled using version 3.4.0.0 of the Cabal library 

## Essential Information

 - **Version**:      
 - **Platform**:     
 - **Installation**: 
 - **Network**:      
vbox@it4us:~/src/cardano-wallet$ lsb_release -a:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
uname -a: 
Linux it4us.top 5.4.0-1032-raspi #35-Ubuntu SMP PREEMPT Fri Mar 19 20:52:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
vbox@it4us:~/src/cardano-wallet$ df -h 
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           782M  4.2M  778M   1% /run
/dev/mmcblk0p2   51G   22G   27G  45% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0       49M   49M     0 100% /snap/core18/1949
/dev/loop1       63M   63M     0 100% /snap/lxd/19648
/dev/loop2       49M   49M     0 100% /snap/core18/1990
/dev/loop3       62M   62M     0 100% /snap/lxd/19206
/dev/loop4       29M   29M     0 100% /snap/snapd/11115
/dev/loop5       27M   27M     0 100% /snap/snapd/11043
/dev/mmcblk0p1  253M  119M  134M  47% /boot/firmware
tmpfs           782M  8.0K  782M   1% /run/user/1001

cat /home/vbox/.cabal/logs/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1.log :
/usr/bin/gcc '-fuse-ld=gold' -Wl,-z,noexecstack /tmp/137041-10.c -o /tmp/137041-11 -E '-D__GLASGOW_HASKELL__=810' '-Dlinux_BUILD_OS=1' '-Daarch64_BUILD_ARCH=1' '-Dlinux_HOST_OS=1' '-Daarch64_HOST_ARCH=1' -Idist/build/autogen -Idist/build/cbits -I./cbits -I. -msse2 -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/unix-2.7.2.2/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/time-1.9.3/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/bytestring-0.10.12.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/base-4.14.1.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/integer-gmp-1.0.3.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/include
/usr/bin/gcc returned ExitFailure 1 with error message:
gcc: error: unrecognized command line option ‘-msse2’

cabal-3.4.0.0: Missing dependency on a foreign library:
* Missing (or bad) header file: crypto_scrypt.h
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
==================== compile uses the -msse2 FLAG =====================
Compiling on arm64  !!!!
# Steps to Reproduce

1. cabal build all 
2. cabal --disable-nix --extra-include-dirs=/usr/include  --extra-lib-dirs=/usr/lib -v3 v2-build all >> /tmp/2021-03-24.err
!!!!!!!!!!!!!^^^^^^^^^^^^^ looks like this works - no it does not !!!!! ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
image
/usr/bin/gcc returned ExitFailure 1 with error message:
gcc: error: unrecognized command line option ‘-msse2’

cabal-3.4.0.0: Missing dependency on a foreign library:
* Missing (or bad) header file: crypto_scrypt.h
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages
================
Failed to build cardano-wallet-core-integration-2021.3.4 because it depends on
cardano-wallet-core-integration-2021.3.4 which itself failed to build.
Failed to build
scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1.
The failure occurred during the configure step.

=====Provided The Following environment settings =================
export LD_LIBRARY_PATH="/usr/local/lib:/usr/lib:"
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
export CI_PROJECT_DIR=/home/vbox
export OS=aarch64
============re-ran with the command line below =======
cabal --extra-include-dirs=/usr/include --extra-lib-dirs=/usr/lib build all

## Actual behavior
should build anything with scrypt: have installed those libraries and include files as shown below
vbox@it4us:~/src/cardano-wallet$ find /usr -name '*scrypt*'
/usr/local/include/sodium/crypto_pwhash_scryptsalsa208sha256.h
/usr/lib/libscrypt.so
/usr/lib/libscrypt.so.0
/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/kdf/scrypt.py
/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/kdf/__pycache__/scrypt.cpython-38.pyc
/usr/lib/python3/dist-packages/nacl/pwhash/scrypt.py
/usr/lib/python3/dist-packages/nacl/pwhash/__pycache__/scrypt.cpython-38.pyc
/usr/lib/libscrypt.a
/usr/bin/scrypt
find: ‘/usr/share/jicofo/.java/.userPrefs’: Permission denied
/usr/share/menu/scrypt
/usr/share/doc/scrypt
/usr/share/doc/libscrypt-dev
/usr/share/doc/libscrypt0
/usr/share/man/man1/scrypt.1.gz
/usr/share/man/man7/scrypt.7ssl.gz
/usr/src/linux-raspi-headers-5.4.0-1030/include/linux/fscrypt.h
/usr/src/linux-raspi-headers-5.4.0-1030/include/uapi/linux/fscrypt.h
/usr/src/linux-raspi-headers-5.4.0-1032/include/linux/fscrypt.h
/usr/src/linux-raspi-headers-5.4.0-1032/include/uapi/linux/fscrypt.h
/usr/include/linux/fscrypt.h
vbox@it4us:~/src/cardano-wallet$ find /usr -name '*scrypt*'
/usr/local/include/sodium/crypto_pwhash_scryptsalsa208sha256.h
/usr/lib/libscrypt.so <======
/usr/lib/libscrypt.so.0 <======
/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/kdf/scrypt.py <======
/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/kdf/__pycache__/scrypt.cpython-38.pyc
/usr/lib/python3/dist-packages/nacl/pwhash/scrypt.py
/usr/lib/python3/dist-packages/nacl/pwhash/__pycache__/scrypt.cpython-38.pyc
/usr/lib/libscrypt.a <======
/usr/bin/scrypt <======
find: ‘/usr/share/jicofo/.java/.userPrefs’: Permission denied
/usr/share/menu/scrypt <======
/usr/share/doc/scrypt<======
/usr/share/doc/libscrypt-dev <======
/usr/share/doc/libscrypt0 <======
/usr/share/man/man1/scrypt.1.gz <======
/usr/share/man/man7/scrypt.7ssl.gz <======
/usr/src/linux-raspi-headers-5.4.0-1030/include/linux/fscrypt.h
/usr/src/linux-raspi-headers-5.4.0-1030/include/uapi/linux/fscrypt.h
/usr/src/linux-raspi-headers-5.4.0-1032/include/linux/fscrypt.h
/usr/src/linux-raspi-headers-5.4.0-1032/include/uapi/linux/fscrypt.h
/usr/include/linux/fscrypt.h
/usr/include/libscrypt.h <======

---

# Resolution

non-arm related flags are set 
arm64 related flags not discovered/configured/configurable
This may be refined as the investigation progresses.
need to set aarch64  flag in c-compiler
=====Provided The Following environment settings =================
export LD_LIBRARY_PATH="/usr/local/lib:/usr/lib:"
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
export CI_PROJECT_DIR=/home/vbox
export OS=aarch64
============re-ran with the command line below =======
cabal --extra-include-dirs=/usr/include --extra-lib-dirs=/usr/lib build all

# QA

Not built/tested on arm processor 
============================!!!!NOTE!!!!==================================
./dist-newstyle/src/cardano-n_-156536db9a177fb0/cardano-node/ChangeLog.md
says and I quote: <-
### ledger changes
- Remove support for HD addresses (not needed by the ledger, just wallets)
- Remove unnecessary SafeSigner abstraction
- Remove unnecessary EncryptedSigningKey
- Remove dependency on scrypt <<======================
- Add tests for isRedeemAddress, improve address encoding/decoding
->
scrypt library and executable are natively available on arm - but it is still included for INTEL processors
????==================How to remove scrypt from the build/dependency list and have it locally linked.==========????
# BUILD LOG
at /home/vbox/.cabal/logs/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1.log 
Using Parsec parser
Configuring library for scrypt-0.5.0..
creating dist/build
/home/vbox/.ghcup/bin/ghc-8.10.4 --numeric-version
/home/vbox/.ghcup/bin/ghc-8.10.4 is version 8.10.4
/home/vbox/.ghcup/bin/ghc-pkg-8.10.4 --version
/home/vbox/.ghcup/bin/ghc-pkg-8.10.4 is version 8.10.4
/home/vbox/.ghcup/bin/ghc-8.10.4 --supported-languages
/home/vbox/.ghcup/bin/ghc-8.10.4 --info
Reading installed packages...
/home/vbox/.ghcup/bin/ghc-pkg-8.10.4 dump --global -v0
/home/vbox/.ghcup/bin/ghc-pkg-8.10.4 dump '--package-db=/home/vbox/.cabal/store/ghc-8.10.4/package.db' -v0
/home/vbox/.ghcup/bin/ghc-8.10.4 --print-libdir -hide-all-packages
Finalized package description:
cabal-version: >=1.8
name: scrypt
version: 0.5.0
license: BSD3
license-file: LICENSE
copyright: Copyright 2011 Falko Peters
maintainer: Falko Peters <falko.peters@gmail.com>
author: Falko Peters <falko.peters@gmail.com>
stability: experimental
homepage: http://github.com/informatikr/scrypt
bug-reports: http://github.com/informatikr/scrypt/issues
synopsis:
Stronger password hashing via sequential memory-hard functions.

description:
This package provides bindings to Colin Percival's `scrypt`
implementation (<http://www.tarsnap.com/scrypt.html>). Scrypt is a key
derivation function designed to be far more secure against hardware
brute-force attacks than alternative functions such as PBKDF2 or bcrypt.
.
Details of the scrypt key derivation function are given in a paper by
Colin Percival, Stronger Key Derivation via Sequential Memory-Hard
Functions: <http://www.tarsnap.com/scrypt/scrypt.pdf>.

category: Cryptography
build-type: Simple
extra-source-files:
README.markdown
cbits/crypto_scrypt.h
cbits/sha256.h
cbits/sysendian.h

source-repository head
type: git
location: http://github.com/informatikr/scrypt

library
exposed-modules: Crypto.Scrypt
cc-options: -msse2
c-sources:
cbits/crypto_scrypt-sse.c
cbits/sha256.c

hs-source-dirs: src
include-dirs: cbits
includes: crypto_scrypt.h
install-includes: crypto_scrypt.h
ghc-options: -Wall
ghc-prof-options: -auto-all
build-depends:
base (>=4 && <5) && ==4.14.1.0,
base64-bytestring >=0.1 && ==1.1.0.0,
bytestring >=0.9 && ==0.10.12.0,
entropy >=0.2 && ==0.4.1.6

test-suite scrypt-test
type: exitcode-stdio-1.0
main-is: Test.hs
hs-source-dirs: test
ghc-options: -Wall
ghc-prof-options: -auto-all
build-depends:
HUnit >=1.2,
QuickCheck >=2 && <3,
base (>=4 && <5) && ==4.14.1.0,
bytestring >=0.9 && ==0.10.12.0,
scrypt,
test-framework >=0.6,
test-framework-hunit >=0.2,
test-framework-quickcheck2 >=0.2
Expanding glob 'README.markdown' in directory './.'.
Expanding glob 'cbits/crypto_scrypt.h' in directory './.'.
Expanding glob 'cbits/sha256.h' in directory './.'.
Expanding glob 'cbits/sysendian.h' in directory './.'.
Dependency base ==4.14.1.0: using base-4.14.1.0
Dependency base64-bytestring ==1.1.0.0: using base64-bytestring-1.1.0.0
Dependency bytestring ==0.10.12.0: using bytestring-0.10.12.0
Dependency entropy ==0.4.1.6: using entropy-0.4.1.6
Searching for alex in path.
Cannot find alex on the path
Searching for ar in path.
Found ar at /usr/bin/ar
Searching for c2hs in path.
Cannot find c2hs on the path
Searching for cpphs in path.
Cannot find cpphs on the path
Searching for doctest in path.
Cannot find doctest on the path
Searching for gcc in path.
Found gcc at /usr/bin/gcc
/usr/bin/gcc -dumpversion
/usr/bin/gcc is version 9
Searching for ghcjs in path.
Cannot find ghcjs on the path
Searching for ghcjs-pkg in path.
Cannot find ghcjs-pkg on the path
Searching for greencard in path.
Cannot find greencard on the path
looking for tool haddock near compiler in /home/vbox/.ghcup/bin
candidate locations:
["/home/vbox/.ghcup/bin/haddock-ghc-8.10.4","/home/vbox/.ghcup/bin/haddock-8.10.4","/home/vbox/.ghcup/bin/haddock","/home/vbox/.ghcup/ghc/8.10.4/bin/haddock-ghc-8.10.4","/home/vbox/.ghcup/ghc/8.10.4/bin/haddock-8.10.4","/home/vbox/.ghcup/ghc/8.10.4/bin/haddock"]
found haddock in /home/vbox/.ghcup/bin/haddock-8.10.4
/home/vbox/.ghcup/bin/haddock-8.10.4 --version
/home/vbox/.ghcup/bin/haddock-8.10.4 is version 2.24.0
Searching for happy in path.
Cannot find happy on the path
Searching for hmake in path.
Cannot find hmake on the path
looking for tool hpc near compiler in /home/vbox/.ghcup/bin
candidate locations:
["/home/vbox/.ghcup/bin/hpc-ghc-8.10.4","/home/vbox/.ghcup/bin/hpc-8.10.4","/home/vbox/.ghcup/bin/hpc","/home/vbox/.ghcup/ghc/8.10.4/bin/hpc-ghc-8.10.4","/home/vbox/.ghcup/ghc/8.10.4/bin/hpc-8.10.4","/home/vbox/.ghcup/ghc/8.10.4/bin/hpc"]
found hpc in /home/vbox/.ghcup/bin/hpc-8.10.4
/home/vbox/.ghcup/bin/hpc-8.10.4 version
/home/vbox/.ghcup/bin/hpc-8.10.4 is version 0.68
looking for tool hsc2hs near compiler in /home/vbox/.ghcup/bin
candidate locations:
["/home/vbox/.ghcup/bin/hsc2hs-ghc-8.10.4","/home/vbox/.ghcup/bin/hsc2hs-8.10.4","/home/vbox/.ghcup/bin/hsc2hs","/home/vbox/.ghcup/ghc/8.10.4/bin/hsc2hs-ghc-8.10.4","/home/vbox/.ghcup/ghc/8.10.4/bin/hsc2hs-8.10.4","/home/vbox/.ghcup/ghc/8.10.4/bin/hsc2hs"]
found hsc2hs in /home/vbox/.ghcup/bin/hsc2hs-8.10.4
/home/vbox/.ghcup/bin/hsc2hs-8.10.4 --version
/home/vbox/.ghcup/bin/hsc2hs-8.10.4 is version 0.68.7
Searching for HsColour in path.
Cannot find HsColour on the path
Searching for jhc in path.
Cannot find jhc on the path
Searching for ld.gold in path.
Found ld.gold at /usr/bin/ld.gold
Environment: [("DBUS_SESSION_BUS_ADDRESS","unix:path=/run/user/1001/bus"),("HASKELL_DIST_DIR","dist"),("HOME","/home/vbox"),("LANG","C.UTF-8"),("LD_LIBRARY_PATH","/usr/local/lib:"),("LESSCLOSE","/usr/bin/lesspipe %s %s"),("LESSOPEN","| /usr/bin/lesspipe %s"),("LOGNAME","vbox"),("LS_COLORS","rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"),("MOTD_SHOWN","pam"),("OLDPWD","/usr/include"),("PATH","/home/vbox/.local/bin:/home/vbox/.cabal/bin:/home/vbox/.ghcup/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vbox/.cabal/bin"),("PKG_CONFIG_PATH","/usr/local/lib/pkgconfig:"),("PWD","/home/vbox/src/cardano-wallet"),("SHELL","/bin/bash"),("SHLVL","2"),("SSH_CLIENT","192.168.0.138 57172 22"),("SSH_CONNECTION","192.168.0.138 57172 192.168.0.136 22"),("SSH_TTY","/dev/pts/4"),("TERM","xterm-256color"),("USER","vbox"),("XDG_DATA_DIRS","/usr/local/share:/usr/share:/var/lib/snapd/desktop"),("XDG_RUNTIME_DIR","/run/user/1001"),("XDG_SESSION_CLASS","user"),("XDG_SESSION_ID","38"),("XDG_SESSION_TYPE","tty"),("_","/home/vbox/.ghcup/bin/cabal")]
/home/vbox/.ghcup/bin/ghc-8.10.4 -hide-all-packages -c /tmp/206414-0.c -o /tmp/206414-1.o -hide-all-packages
/usr/bin/ld.gold -x -r /tmp/206414-1.o -o /tmp/206414-2.o
Searching for pkg-config in path.
Found pkg-config at /usr/bin/pkg-config
/usr/bin/pkg-config --version
/usr/bin/pkg-config is version 0.29.1
looking for tool runghc near compiler in /home/vbox/.ghcup/bin
candidate locations:
["/home/vbox/.ghcup/bin/runghc-ghc-8.10.4","/home/vbox/.ghcup/bin/runghc-8.10.4","/home/vbox/.ghcup/bin/runghc","/home/vbox/.ghcup/ghc/8.10.4/bin/runghc-ghc-8.10.4","/home/vbox/.ghcup/ghc/8.10.4/bin/runghc-8.10.4","/home/vbox/.ghcup/ghc/8.10.4/bin/runghc"]
found runghc in /home/vbox/.ghcup/bin/runghc-8.10.4
/home/vbox/.ghcup/bin/runghc-8.10.4 --version
/home/vbox/.ghcup/bin/runghc-8.10.4 is version 8.10.4
Searching for strip in path.
Found strip at /usr/bin/strip
/usr/bin/strip --version
/usr/bin/strip is version 2.34
Searching for tar in path.
Found tar at /usr/bin/tar
/usr/bin/tar --help
Searching for uhc in path.
Cannot find uhc on the path
Source component graph: component lib
Configured component graph:
    component scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1
        include base-4.14.1.0
        include base64-bytestring-1.1.0.0-c0daccf83be46305c0ad726e5454703a7861bd5dfbc0c537db7a2219ba7f1cb3
        include bytestring-0.10.12.0
        include entropy-0.4.1.6-dcacce33066287d1e698ba0fe0b4d4d4ab043f6088cbc0fc59db736d78399eb7
Linked component graph:
    unit scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1
        include base-4.14.1.0
        include base64-bytestring-1.1.0.0-c0daccf83be46305c0ad726e5454703a7861bd5dfbc0c537db7a2219ba7f1cb3
        include bytestring-0.10.12.0
        include entropy-0.4.1.6-dcacce33066287d1e698ba0fe0b4d4d4ab043f6088cbc0fc59db736d78399eb7
        Crypto.Scrypt=scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1:Crypto.Scrypt
Ready component graph:
    definite scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1
        depends base-4.14.1.0
        depends base64-bytestring-1.1.0.0-c0daccf83be46305c0ad726e5454703a7861bd5dfbc0c537db7a2219ba7f1cb3
        depends bytestring-0.10.12.0
        depends entropy-0.4.1.6-dcacce33066287d1e698ba0fe0b4d4d4ab043f6088cbc0fc59db736d78399eb7
Using Cabal-3.4.0.0 compiled by ghc-8.10
Using compiler: ghc-8.10.4
Using install prefix:
/home/vbox/.cabal/store/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1
Executables installed in:
/home/vbox/.cabal/store/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1/bin
Libraries installed in:
/home/vbox/.cabal/store/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1/lib
Dynamic Libraries installed in:
/home/vbox/.cabal/store/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1/lib
Private executables installed in:
/home/vbox/.cabal/store/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1/libexec
Data files installed in:
/home/vbox/.cabal/store/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1/share
Documentation installed in:
/home/vbox/.cabal/store/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1/share/doc
Configuration files installed in:
/home/vbox/.cabal/store/ghc-8.10.4/scrypt-0.5.0-f1ad902c29f7d19711cbc85c86cd3df6a7b960ac14a11a79852460a14b8b51c1/etc
No alex found
Using ar found on system at: /usr/bin/ar
No c2hs found
No cpphs found
No doctest found
Using gcc version 9 found on system at: /usr/bin/gcc
Using ghc version 8.10.4 given by user at: /home/vbox/.ghcup/bin/ghc-8.10.4
Using ghc-pkg version 8.10.4 given by user at:
/home/vbox/.ghcup/bin/ghc-pkg-8.10.4
No ghcjs found
No ghcjs-pkg found
No greencard found
Using haddock version 2.24.0 found on system at:
/home/vbox/.ghcup/bin/haddock-8.10.4
No happy found
Using haskell-suite found on system at: haskell-suite-dummy-location
Using haskell-suite-pkg found on system at: haskell-suite-pkg-dummy-location
No hmake found
Using hpc version 0.68 found on system at: /home/vbox/.ghcup/bin/hpc-8.10.4
Using hsc2hs version 0.68.7 found on system at:
/home/vbox/.ghcup/bin/hsc2hs-8.10.4
No hscolour found
No jhc found
Using ld found on system at: /usr/bin/ld.gold
Using pkg-config version 0.29.1 found on system at: /usr/bin/pkg-config
Using runghc version 8.10.4 found on system at:
/home/vbox/.ghcup/bin/runghc-8.10.4
Using strip version 2.34 found on system at: /usr/bin/strip
Using tar found on system at: /usr/bin/tar
No uhc found
/usr/bin/gcc '-fuse-ld=gold' -Wl,-z,noexecstack /tmp/206414-4.c -o /tmp/206414-5 '-D__GLASGOW_HASKELL__=810' '-Dlinux_BUILD_OS=1' '-Daarch64_BUILD_ARCH=1' '-Dlinux_HOST_OS=1' '-Daarch64_HOST_ARCH=1' -Idist/build/autogen -Idist/build/cbits -I./cbits -I. -msse2 -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/unix-2.7.2.2/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/time-1.9.3/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/bytestring-0.10.12.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/base-4.14.1.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/integer-gmp-1.0.3.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/include -msse2 -L/home/vbox/.cabal/store/ghc-8.10.4/entropy-0.4.1.6-dcacce33066287d1e698ba0fe0b4d4d4ab043f6088cbc0fc59db736d78399eb7/lib -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/unix-2.7.2.2 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/time-1.9.3 -L/home/vbox/.cabal/store/ghc-8.10.4/base64-bytestring-1.1.0.0-c0daccf83be46305c0ad726e5454703a7861bd5dfbc0c537db7a2219ba7f1cb3/lib -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/bytestring-0.10.12.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/deepseq-1.4.4.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/array-0.5.4.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/base-4.14.1.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/integer-gmp-1.0.3.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/ghc-prim-0.6.1 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/rts
/usr/bin/gcc returned ExitFailure 1 with error message:
gcc: error: unrecognized command line option ‘-msse2’
gcc: error: unrecognized command line option ‘-msse2’
/usr/bin/gcc '-fuse-ld=gold' -Wl,-z,noexecstack /tmp/206414-6.c -o /tmp/206414-7 -L/home/vbox/.cabal/store/ghc-8.10.4/entropy-0.4.1.6-dcacce33066287d1e698ba0fe0b4d4d4ab043f6088cbc0fc59db736d78399eb7/lib -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/unix-2.7.2.2 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/time-1.9.3 -L/home/vbox/.cabal/store/ghc-8.10.4/base64-bytestring-1.1.0.0-c0daccf83be46305c0ad726e5454703a7861bd5dfbc0c537db7a2219ba7f1cb3/lib -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/bytestring-0.10.12.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/deepseq-1.4.4.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/array-0.5.4.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/base-4.14.1.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/integer-gmp-1.0.3.0 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/ghc-prim-0.6.1 -L/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/rts
/usr/bin/gcc '-fuse-ld=gold' -Wl,-z,noexecstack /tmp/206414-8.c -o /tmp/206414-9 -c '-D__GLASGOW_HASKELL__=810' '-Dlinux_BUILD_OS=1' '-Daarch64_BUILD_ARCH=1' '-Dlinux_HOST_OS=1' '-Daarch64_HOST_ARCH=1' -Idist/build/autogen -Idist/build/cbits -I./cbits -I. -msse2 -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/unix-2.7.2.2/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/time-1.9.3/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/bytestring-0.10.12.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/base-4.14.1.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/integer-gmp-1.0.3.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/include -msse2
/usr/bin/gcc returned ExitFailure 1 with error message:
gcc: error: unrecognized command line option ‘-msse2’
gcc: error: unrecognized command line option ‘-msse2’
/usr/bin/gcc '-fuse-ld=gold' -Wl,-z,noexecstack /tmp/206414-10.c -o /tmp/206414-11 -E '-D__GLASGOW_HASKELL__=810' '-Dlinux_BUILD_OS=1' '-Daarch64_BUILD_ARCH=1' '-Dlinux_HOST_OS=1' '-Daarch64_HOST_ARCH=1' -Idist/build/autogen -Idist/build/cbits -I./cbits -I. -msse2 -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/unix-2.7.2.2/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/time-1.9.3/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/bytestring-0.10.12.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/base-4.14.1.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/integer-gmp-1.0.3.0/include -I/home/vbox/.ghcup/ghc/8.10.4/lib/ghc-8.10.4/include
/usr/bin/gcc returned ExitFailure 1 with error message:
gcc: error: unrecognized command line option ‘-msse2’

cabal-3.4.0.0: Missing dependency on a foreign library:
* Missing (or bad) header file: crypto_scrypt.h
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.

# Jira ticket

ADP-842

### PR DESCRIPTION
**Pull request by rvl**
### Issue Number

ADP-842
Fixes #2578.

### Overview

- Adds cabal flag so that cardano-wallet can be compiled without the `scrypt` package.
- Replaces `scrypt` with `cryptonite` for the integration tests only

If `scrypt` does not compile for your target system, then disable it with:

```
cabal configure --disable-tests --enable-benchmarks -f-scrypt
```

### Comments

I'm not too keen on changing the scrypt package in the main code, for the time being. But we can replace this package in the integration tests, without too much risk.

Need to use conditional modules instead of CPP because that breaks stylish-haskell.

### CODE REVIEW

File: lib/core-integration/src/Test/Integration/Framework/DSL.hs [hunk 1]
```diff
@@ -1248,17 +1250,19 @@ emptyRandomWalletWithPasswd ctx rawPwd = do
...
-    encryptPasswordWithScrypt =
-        fmap Scrypt.getEncryptedPass
-        . Scrypt.encryptPassIO Scrypt.defaultParams
-        . Scrypt.Pass
+    scrypt = encryptPasswordWithScrypt
         . CBOR.toStrictByteString
         . CBOR.encodeBytes
         . BA.convert
 
+encryptPasswordWithScrypt :: (BA.ByteArrayAccess a, BA.ByteArray b) => a -> IO b
```
Comment (HeinrichApfelmus) [inline lib/core-integration/src/Test/Integration/Framework/DSL.hs]: For posterity: The documentation of the `scrypt` package notes that the ByteString returned by `Scrypt.getEncryptedPass` contains not just the encrypted password, but also the parameters and salt used to encrypt it. In contrast, the `generate` function from the `cryptonite` package only seems to return that encrypted password.

The difference does not matter for the integration test, but it would matter for legacy wallets (hence the choice to keep the `scrypt` dependency in the core library.)

**Review by HeinrichApfelmus — APPROVED** [review]
Looks good to me!

File: lib/core-integration/src/Test/Integration/Framework/DSL.hs (hunk 1 above)
Comment (rvl) [reply lib/core-integration/src/Test/Integration/Framework/DSL.hs]: Yes good point - thanks - this will need fixing.

**Comment by ghost** [comment]
I can confirm that without scrypt you can build v2021-09-09 of the cardano wallet on ARM64 without any further issue. I wanted to use it on the paper wallet terminal with cardano-python for testing. Which uses a raspberry pi. Just so you know it is smooth sailing after this :+1:

**Comment by hamishmack** [comment]
I have merged in the latest `master` branch so that we can try this out for testing `daedalus` on `aarch64-darwin`.  There were quite a few conflicts most of which related to adjacent changes to `import` statements.

**Comment by bakon11** [comment]
> I can confirm that without scrypt you can build v2021-09-09 of the cardano wallet on ARM64 without any further issue. I wanted to use it on the paper wallet terminal with cardano-python for testing. Which uses a raspberry pi. Just so you know it is smooth sailing after this +1

Hi, 

How were you able to build it without scrypt? I am trying to build `v2021-11-11`.

I'm running: 
`cabal configure --disable-tests --enable-benchmarks -f-scrypt` 

And it still shows me that `scrypt-0.5.0` needs to build and attempts to build it on `cabal build all` command.

Thanks.

**Comment by ghost** [comment]
@bakon11 Was just to check if there were major hurdles beyond this. I removed all references to scrypt in the source code. Not recommended to really use it this way. IMHO, I am not an expert. The nix build of this repository worked like this 'nix-build -A cardano-wallet'. But it requires a lot of storage space.

**Comment by bakon11** [comment]
> @bakon11 Was just to check if there were major hurdles beyond this. I removed all references to scrypt in the source code. Not recommended to really use it this way. IMHO, I am not an expert. The nix build of this repository worked like this 'nix-build -A cardano-wallet'. But it requires a lot of storage space.

gotcha, so the scrypt flag that should signal cabal not to build it, won't work if there is actual references to scrypt  in the source correct?

Yeah, I agree removing it is not the best solution, but it's a solution to help keep on building a proof of concept project until a real fix is available.

**Comment by ghost** [comment]
> gotcha, so the scrypt flag that should signal cabal not to build it, won't work if there is actual references to scrypt in the source correct?
> 
> Yeah, I agree removing it is not the best solution, but it's a solution to help keep on building a proof of concept project until a real fix is available.

Yes indeed. What are you building? If you want to discuss you can find me on my discord here [M2tec discord](https://discord.gg/HUQQKtkxdz)

**Comment by angerman** [comment]
@HeinrichApfelmus, @rvl can we get this over the line? I've run into this today.

**Comment by rvl** [comment]
Will be updating this PR soon, please hold tight.

**Comment by chisNaN** [comment]
Hello thanks for the work
any news about this update?
Waiting the arm version to install daedalus on mac m1 pro

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
@rvl If you're back tomorrow — I found something interesting:

In this PR `cborify` is apart of `preparePassphrase :: Passphrase "user" -> Passphrase "encryption`, whereas on `master` it is not. On master, `cborify` is instead called by `checkPassphrase`.

Because it's the `Passphrase "encryption"` that is passed alongside the `XPrv` when signing, whether or not `cborify` is "apart" of `Passphrase "encryption"` matters, and a change in behaviour would silently make the `XPrv` incorrect when decrypted from a `Scrypt` passphrase. The integration tests pass with both variants with `EncryptUsingScrypt` as `currentPassphraseScheme`.

I think `EncryptUsingScrypt` is mainly used from the restore-from-`secret.key` feature. Looking at the linked issue of ADP-1335 and TSD reports it sounds like there are many cases of users with secret.key wallets who can't spend their funds. Could it be that restoration from `secret.key`s never actually worked? 🤔 (in the sense that funds could be spent)

https://github.com/input-output-hk/cardano-sl/blob/1a792d7cd0f0c93a0f0c28f66372bce3c3808dbd/crypto/Pos/Crypto/Signing/Safe.hs#L48 

Looking at this... it seems it's calling `cardano-crypto` with the _raw_ passphrase — suggesting `preparePassphrase` should be `id` — and we should encode it to CBOR before calling `Scrypt.encryptPass`, but not hash it. However comments and goldens in cardano-wallet seem to be fairly confident there's hashing involved... 🤷‍♂️   will look more tomorrow...

<details>
<summary>Details: implementation on master vs this PR</summary>

### On master

```haskell
-- | Manipulation done on legacy passphrases before getting encrypted.
preparePassphrase
    :: PassphraseScheme
    -> Passphrase "raw"
    -> Passphrase "encryption"
preparePassphrase = \case
    EncryptWithPBKDF2 -> coerce
    EncryptWithScrypt -> Passphrase . hashMaybe
  where
    hashMaybe pw@(Passphrase bytes)
        | pw == mempty = BA.convert bytes
        | otherwise = BA.convert $ blake2b256 bytes

-- | Check whether a 'Passphrase' matches with a stored 'Hash'
checkPassphrase
    :: PassphraseScheme
    -> Passphrase "raw"
    -> Hash "encryption"
    -> Either ErrWrongPassphrase ()
checkPassphrase scheme received stored = do
    let prepared = preparePassphrase scheme received
    case scheme of
        EncryptWithPBKDF2 -> do
            salt <- getSalt stored
            unless (constantTimeEq (encryptPassphrase prepared salt) stored) $
                Left ErrWrongPassphrase
        EncryptWithScrypt -> do
            let msg = Scrypt.Pass
                    $ CBOR.toStrictByteString
                    $ CBOR.encodeBytes
                    $ BA.convert prepared
            if Scrypt.verifyPass' msg (Scrypt.EncryptedPass (getHash stored))
                then Right ()
                else Left ErrWrongPassphrase
```

### In this PR

```haskell
checkPassphrase :: Passphrase "encryption" -> PassphraseHash -> Maybe Bool
checkPassphrase pwd stored = Just $ verifyPass' pass encryptedPass
  where
    pass = Pass (BA.convert pwd)
    encryptedPass = EncryptedPass (BA.convert stored)

preparePassphrase :: Passphrase "user" -> Passphrase "encryption"
preparePassphrase = Passphrase . cborify . hashMaybe . unPassphrase
  where
    hashMaybe pw
        | pw == mempty = mempty
        | otherwise = BA.convert $ blake2b256 pw

    cborify = BA.convert . CBOR.toStrictByteString . CBOR.encodeBytes
```

</details>

File: lib/core/test/unit/Cardano/WalletSpec.hs [hunk 2]
```diff
@@ -275,6 +275,8 @@ import qualified Cardano.Wallet.DB.MVar as MVar
 import qualified Cardano.Wallet.DB.Sqlite as Sqlite
 import qualified Cardano.Wallet.DB.Sqlite.AddressBook as Sqlite
 import qualified Cardano.Wallet.Primitive.Migration as Migration
+import Cardano.Wallet.Primitive.Passphrase.Current
+    ( preparePassphrase )
```
Comment (Anviking) [inline lib/core/test/unit/Cardano/WalletSpec.hs]: 👀

File: lib/core/src/Cardano/Wallet/Api/Server.hs [hunk 3]
```diff
@@ -4048,6 +4061,12 @@ instance IsServerError ErrWithRootKey where
                 , "to encrypt the root private key of the given wallet: "
                 , toText wid
                 ]
+        ErrWithRootKeyWrongPassphrase wid (ErrPassphraseSchemeUnsupported s) ->
+            apiError err501 WrongEncryptionPassphrase $ mconcat
+                [ "This build is not compiled with support for the "
+                , toText s <> " scheme used by the given wallet: "
+                , toText wid
+                ]
```
Comment (Anviking) [inline lib/core/src/Cardano/Wallet/Api/Server.hs:4079]: 👍

**Review by Anviking — APPROVED** [review]
LGTM. I suspect the `hashMaybe` we have on master wrong, but that's separate from this PR. I added a few goldens for PBKDF2 passwords as extra sanity check that this doesn't break anything.

**Comment by Anviking** [comment]
bors try

**Comment by Anviking** [comment]
@rvl if you're ok with this we can merge

**Comment by rvl** [comment]
I checked it and rebased again. It looks good to merge.

**Comment by chisNaN** [comment]
Hello I have been following this topic and this one also https://github.com/input-output-hk/daedalus/issues/2677
My question is the release of the apple silicon version wallet will happen soon?

Thanks

**Comment by gaytomycode** [comment]
any update on the scrypt issue? I'm getting this on an apple m1. I tried using the flag mentioned in the thread above and same error 
`cabal: Failed to build scrypt-0.5.0 (which is required by test:unit from cardano-wallet-core-2022.4.27).`
