### PR TITLE
Metadata encryption bug

### LINKED ISSUE #5017: Metadata encryption property test fails
Release pipeline failed with [this failure](https://buildkite.com/cardano-foundation/cardano-wallet/builds/9546#0195534c-801d-4689-935e-6ae98abd3d6e/22-3840) in unit tests which I was able to 
reproduce locally using seed. 

Doing some experiments locally, I found out that if a password is shorter than 64 bytes, extending it with `\NUL` bytes up to 64 bytes yields identical encryption keys. The following property demonstrates this behaviour:

```haskell
prop_pbkdf2_null_suffixed_passwords_shorter_than_64_bytes_are_equivalent
    :: Property
prop_pbkdf2_null_suffixed_passwords_shorter_than_64_bytes_are_equivalent =
    forAll passwords $ \pwd ->
        forAllShrink (nullExtended pwd) (shrinkNulls pwd) $ \pwd2 ->
            forAll salts $ \slt ->
                let key1 = PBKDF2.generateKey metadataPBKDF2Config pwd (Just slt)
                    key2 = PBKDF2.generateKey metadataPBKDF2Config pwd2 (Just slt)
                in  key1 === key2
                        & tabulate "password length" [bucketed 8 $ BS.length pwd]
                        & tabulate
                            "suffix length"
                            [bucketed 8 $ BS.length pwd2 - BS.length pwd]
                        & counterexample
                            ("suffix len: " <> show (BS.length pwd2 - BS.length pwd))
                        & counterexample
                            ("pwd len: " <> show (BS.length pwd))
  where
    passwords =
        BS.pack <$> do
            len <- choose (1, 63)
            vectorOf len arbitrary
    salts = BS.pack <$> arbitrary
    nullExtended bs = do
        suffixLen <- choose (1, 64 - BS.length bs)
        pure $ bs <> BS.replicate suffixLen 0
    shrinkNulls pwd pwd2
        | pwd2 == pwd = []
        | otherwise = [BS.dropEnd 1 pwd2]
    bucketed size num =
        let lb = num `div` size
        in  ("<= " <> show ((lb + 1) * size))
```

A sample run gives:

```
> quickCheck $ withMaxSuccess 1000 prop_pbkdf2_null_suffixed_passwords_shorter_than_64_bytes_are_equivalent
+++ OK, passed 1000 tests.

password length (1000 in total):
14.3% <= 48
14.2% <= 32
12.9% <= 40
12.8% <= 16
12.5% <= 56
12.4% <= 64
10.7% <= 24
10.2% <= 8

suffix length (1000 in total):
35.4% <= 8
22.5% <= 16
14.8% <= 24
10.0% <= 32
 8.0% <= 40
 5.1% <= 48
 3.1% <= 56
 1.1% <= 64
```

Therefore, the property `prop_passphrase` defined as 

```
prop_passphrase :: TestingSetup -> Expectation
prop_passphrase (TestingSetup payload' pwd1 pwd2 salt') = do
    ( mapLeft
            (const ErrMissingValidEncryptionPayload)
            (toMetadataEncrypted pwd1 payload' (Just salt'))
            >>= fromMetadataEncrypted pwd2
        )
        `shouldSatisfy` isLeft
```

can fail if `pwd2` has `pwd1` as a prefix and just extends it with one or more `\NUL` bytes.

### PR DESCRIPTION
**Pull request by paweljakubas**
The bug was triggered when metadata password shorter than 64 bytes was compared with the same password padded with /NUL (in hex 0x00). It turn out that this is corner case that could appear, indeed!

Reason:
In impl of KDF we are using, ie. PBKDF2 (https://www.ietf.org/rfc/rfc2898.txt) is about successive hashing of the message. And here password (P) and salt (S) are undergoing :
```
H1= Hash( P || S)
H2=Hash (H1)
....
``` 
The culprit is bitwise OR operation. As /NUL is 0x00 it is the same as automatic padding that is done when P is not 64 bytes!

- [x] I have added property with description to document the case in `cyrptographic-primitives`
- [x] `MetadataPassword` was introduced in `MetadataEncryptionSpec` to enforce using alphanumeric character (btw. recommended by openssl):
-> see https://docs.openssl.org/3.1/man1/openssl-kdf/#options
```
pass:string
Specifies the password as an alphanumeric string (use if the password contains printable characters only). The password must be specified for PBKDF2 and scrypt.
```

### Issue Number

fix #5017

### CODE REVIEW

File: lib/crypto-primitives/src/Cryptography/KDF/PBKDF2.hs [hunk 1]
```diff
@@ -56,16 +56,21 @@ generateKey
     :: HashAlgorithm h
     => PBKDF2Config h
     -> ByteString
-    -- ^ payload
+    -- ^ password
```
Comment (paolino) [inline lib/crypto-primitives/src/Cryptography/KDF/PBKDF2.hs:59]: :+1:

File: lib/crypto-primitives/test/Cryptography/KDF/PBKDF2Spec.hs [hunk 2]
```diff
@@ -313,6 +325,17 @@ spec = do
...
             , iv = "FD40C29618D438E3658388C52EB7974E"
             }
+
+    describe "password and password padded with \NUL produce the same (key, iv) pair" $
+        it "generateKey conf passwd salt == generateKey conf (passwd <> \NUL <> ...) salt" $
+        property @(TestCaseSHA256 -> Property) $
+        \(TestCase algo' iters' keyL' ivL' passwd' salt') -> do
+            let nulsToAdd = 64 - BS.length passwd'
+            let passwdPadded = passwd' <> BS.replicate nulsToAdd 0
+            generateKey (PBKDF2Config algo' iters' keyL' ivL') passwd' salt'
```
Comment (paolino) [inline lib/crypto-primitives/test/Cryptography/KDF/PBKDF2Spec.hs:335]: :+1:

File: lib/primitive/test/spec/Cardano/Wallet/Primitive/Types/MetadataEncryptionSpec.hs [hunk 3]
```diff
@@ -433,10 +438,19 @@ spec = do
 fromHexToM :: Text -> Maybe ByteString
 fromHexToM = rightToMaybe . convertFromBase Base16 . T.encodeUtf8
 
+newtype MetadataPassword = MetadataPassword {unPassword :: ByteString}
```
Comment (paolino) [inline lib/primitive/test/spec/Cardano/Wallet/Primitive/Types/MetadataEncryptionSpec.hs:441]: Can we just use a generator and avoid creating types ? Just 2c

**Review by paolino — APPROVED** [review]
Thanks
